var Roblox = Roblox || {};
Roblox.LangDynamic = Roblox.LangDynamic || {};
Roblox.LangDynamic["Authentication.SignUp"] = {
  "Label.ConfirmPassword": "Confirm password",
  "Label.Email": "Email",
  "Response.InvalidBirthday": "Invalid birthday.",
  "Response.PasswordMismatch": "Passwords do not match.",
  "Response.PleaseEnterPassword": "Please enter a password.",
  "Response.PleaseEnterUsername": "Please enter a username.",
  "GuestSignUpAB.Action.SignUp": "Sign Up",
  "Label.Birthday": "Birthday",
  "Label.Gender": "Gender",
  "Label.PasswordRequirements": "Password (min length 8)",
  "Label.UsernameRequirements": "Username (length 3-20, _ is allowed)",
  "Response.BadUsername": "Username not appropriate for Roblox.",
  "Response.InvalidEmail": "Invalid email address.",
  "Response.PasswordComplexity": "Please create a more complex password.",
  "Response.PasswordWrongShort": "Passwords must be at least 8 characters long.",
  "Response.UnknownError": "Sorry! An unknown error occurred. Please try again later.",
  "Response.UsernameAlreadyInUse": "This username is already in use.",
  "Response.UsernameInvalidCharacters": "Only a-z, A-Z, 0-9 and _ are allowed.",
  "Response.UsernameInvalidLength": "Usernames can be 3 to 20 characters long.",
  "Response.UsernameInvalidUnderscore": "Usernames cannot start or end with _.",
  "Response.UsernameNotAvailable": "Username not available. Please try again.",
  "Response.UsernamePrivateInfo": "Username might contain private information.",
  "Response.UsernameTooManyUnderscores": "Usernames can have at most one _.",
  "Label.PleaseAgreeToTerms": "Please agree to our Terms of Use and Privacy Policy.",
  "Label.GenderRequired": "Gender is required.",
  "Label.EmailRequirementsUnder13": "Parent's Email",
  "Response.UsernameExplicit": "This username is not allowed, please try another.",
  "Response.ErrorTryAgain": "Something went wrong. Please try again later.",
  "Action.SignUp": "Sign up",
  "Action.Cancel": "Cancel",
  "Response.UsernameTakenTryAgain": "This username is already taken! Please try a different one.",
  "Response.UsernameInvalid": "Please enter a valid username.",
  "Description.PrivacyPolicy": "Privacy Policy",
  "Description.TermsOfService": "Terms of Service",
  "Response.BirthdayMustBeSetFirst": "Birthday must be set first.",
  "Label.Play": "Play",
  "Label.About": "About",
  "Label.Platforms": "Platforms",
  "Heading.SignupHaveFun": "Sign up and start having fun!",
  "Heading.LoginHaveFun": "Log in and start having fun!",
  "Label.TermsOfUse": "Terms of Use",
  "Response.PasswordContainsUsernameError": "Password shouldn't match username.",
  "Response.TooManyAccountsWithSameEmailError": "Too many accounts use this email.",
  "Response.UsernamePasswordRequired": "Username and Password are required.",
  "Label.Required": "Required",
  "Response.SpaceOrSpecialCharaterError": "Spaces and special characters are not allowed.",
  "Response.UsernameAllowedCharactersError": "Usernames may only contain letters, numbers, and _.",
  "Response.JavaScriptRequired": "JavaScript is required to submit this form.",
  "Label.UsernameHint": "Username (don't use your real name)",
  "Label.SignupButtonText": "Sign Up and Play!",
  "Heading.FacebookSignupAlmostDone": "{firstname}, YOU'RE ALMOST DONE",
  "Label.FacebookSignupUsername": "Create Roblox username:",
  "Action.CreateAccount": "Create Account",
  "Description.AccountLinkingWarning":
    "To link to an existing Roblox account, sign in and link them on the account settings page.",
  "Description.SignUpAgreement":
    "By clicking {spanStart}Sign Up{spanEnd}, you are agreeing to the {termsOfUseLink} including the arbitration clause and you are acknowledging the {privacyPolicyLink}",
  "Action.Submit": "Submit",
  "Response.UsernameOrPasswordIncorrect": "Your username or password is incorrect.",
  "Response.PasswordConfirmation": "Please enter a password confirmation.",
  "Action.LogInCapitalized": "Log In",
  "Label.AlreadyRegistered": "Already registered?",
  "Heading.ConnectFacebook": "Connect to Facebook",
  "Heading.CreateAnAccount": "CREATE AN ACCOUNT",
  "Label.BirthdayWithColumn": "Birthday:",
  "Label.GenderWithColumn": "Gender:",
  "Label.Male": "Male",
  "Label.Female": "Female",
  "Label.DesiredUsername": "Desired Username:",
  "Description.NoRealName": "Do not use your real name.",
  "Label.UsernameCharacterLimit": "3-20 alphanumeric characters, no spaces.",
  "Action.SignupAndSync": "Sign Up & Sync",
  "Response.FacebookConnectionError": "Error while retrieving values from Facebook.",
  "Action.ReturnHome": "Return Home",
  "Response.UsernameRequired": "Username is required.",
  "Response.CaptchaNotEnteredError": "Please fill out the Captcha",
  "Response.CaptchaMismatchError": "Words do not match.",
  "Response.SocialAccountCreationFailed": "Account creation failed",
  "Label.Username": "Username",
  "Message.Username.NoRealNameUse": "Don't use your real name",
  "Label.Password": "Password",
  "Message.Password.MinLength": "Min length 8",
  "Label.Day": "Day",
  "Label.Month": "Month",
  "Label.Year": "Year",
  "Label.FacebookNotLinked":
    "Your Facebook account is not linked to any Roblox account. Please sign up for a Roblox account.",
  "Response.FacebookLoginAge": "Facebook login can only be used by users above 13.",
  "Response.BirthdayInvalid": "This birthday is invalid.",
  "Response.InvalidPhoneNumber": "Invalid phone number.",
  "Response.PhoneNumberAlreadyLinked": "Number is already associated with another account.",
  "Label.PhoneNumber": "Phone Number",
  "Label.SignUpWith": "or sign up with",
  "Response.BadUsernameForWeChat": "Username is not appropriate",
  "Label.UsernameError1": "Contains only letters, numbers, and _",
  "Label.UsernameError2": "Is between 3 and 20 characters long",
  "Label.UsernameError3": "Is not already in use",
  "Label.UsernameError5": "Does not start or end with _",
  "Label.PasswordError1": "Is at least 8 characters long",
  "Label.PasswordError2": "Does not match username",
  "Label.PasswordError3": "Is not a simple password",
  "Heading.PasswordPage": "Create a password",
  "Heading.SelectStartingAvatar": "Select a Starting Character",
  "Label.EmailAddress": "Email Address",
  "Action.LinkAccount": "Link Account",
  "Label.AlreadyHaveRobloxAccount": "Already have a Roblox account?",
  "Heading.CustomizeYourCharacter": "Customize Your Character",
  "Description.ChangeLater": "You can always change this later",
  "Response.GlobalAppAccessError": "The account is unable to log in.",
  "Response.PasswordBadLength": "Passwords must be between 8 and 200 characters long.",
  "Label.OptionalGender": "Gender (optional)",
  "Label.EmailOptional": "Email Address (Optional)",
  "Label.EmailRequirementsUnder13Optional": "Parent's Email (Optional)",
  "Label.PasswordPlaceholder": "At least 8 characters",
  "Label.ParentEmailAddress": "Parent's Email Address",
  "Action.UsePhoneNumber": "Use phone number",
  "Action.UseEmail": "Use email address",
  "Label.RetypePasswordPlaceholder": "Enter your password again",
  "Label.RetypePassword": "Confirm Password",
  "Action.CodeResent": "Code Resent",
  "Response.InvalidPassword": "Invalid password.",
  "Response.UserAccountCreatedButLoginFailed":
    "Account was successfully created but cannot be logged in at this time. Please try again later.",
  "Response.DifferentPasswordRequired":
    "Please use a different password. Use any special characters or numbers.",
  "Label.ErrorAcceptTermsToContinue":
    "You must agree to the Terms of Use and acknowledge the Privacy Policy to continue",
  "Description.VerifiedParentalConsentEmail.Body":
    "{paragraphStart}Your child is requesting to create the account {emphasisStart}{userName}{emphasisEnd} on Roblox, an online entertainment platform that enables kids to imagine, create, and play together in immersive, user-generated 3D worlds.{paragraphEnd}{paragraphStart}Your child has provided us with a username, date of birth, and a parent's email address to create an account. In order for your child to complete the account creation process, you must consent to your child’s use of Roblox. You must enter the code below to complete the sign up flow and consent to your child’s use of Roblox. By entering the code, you and your child agree to the Roblox {aTagStartWithHref}{termsLink}{hrefEnd}Terms{aTagEnd}, including arbitration, and (b) You will supervise and be solely responsible for your child’s use of Roblox.{paragraphEnd}{paragraphStart}{emphasisStart}Verification Code: {code}{emphasisEnd}{paragraphEnd}{lineBreak}{paragraphStart}{emphasisStart}Parent's Guide To Roblox{emphasisEnd}{paragraphEnd}{paragraphStart}We recommend that you visit our {aTagStartWithHref}{parentsLink}{hrefEnd}Parent’s Guide{aTagEnd} to help yourself get acquainted with our platform and find helpful tips for creating a positive experience for your kids on Roblox.{paragraphEnd}{paragraphStart}{emphasisStart}Privacy{emphasisEnd}{paragraphEnd}{paragraphStart}You may remove your child's account anytime by contacting customer service at {aTagStartWithHref}{supportLink}{hrefEnd}https://www.roblox.com/support{aTagEnd}. Your email will not be used for any other purpose, disclosed to third parties, or combined with any other personal information collected from your child. Please review our {aTagStartWithHref}{privacyPolicyLink}{hrefEnd}Privacy Policy{aTagEnd} for more information.{paragraphEnd}",
  "Description.VerifiedParentalConsentEmail.Links":
    "{aTagStartWithHref}{TwoStepVerificationArticleLink}{hrefEnd}Learn More{aTagEnd} | {aTagStartWithHref}{AccountSafetyArticleLink}{hrefEnd}Account Safety{aTagEnd} | {aTagStartWithHref}{supportPageLink}{hrefEnd}Support{aTagEnd}",
  "Description.VerifiedParentalConsentEmail.Footer":
    "Do not reply to this email directly. You are receiving this email because there has been an attempt to sign up for a Roblox account with your email. If you did not make this request, please disregard this email.",
  "Description.VerifiedParentalConsentEmail.Subject": "Approval Request To Sign Up For Roblox",
  "Description.VerifiedParentalConsentModal.EnterEmail":
    "Enter your parent's email address to receive a verification code. ",
  "Label.VerifiedParentalConsentModal.ExampleEmail": "example@email.com",
  "Heading.VerifiedParentalConsentModal.AddHeader": "Add Parent's Email",
  "Heading.VerifiedParentalConsentModal.VerifyHeader": "Verify Your Parent's Email",
  "Description.VerifiedParentalConsentModal.EnterCode": "Enter the code we just sent to {email}",
  "Label.VerifiedParentalConsentModal.ChangeEmail": "Change Email Address",
  "Description.VerifiedParentalConsentModal.EnterContinue":
    "By entering the code and clicking Continue, you are giving consent to your child to access Roblox.",
  "Action.VerifiedParentalConsentModal.ResendCode": "Resend Code ({time})",
  "Description.EnterParentEmail":
    "Enter your parent's email address to receive a verification code.",
  "Label.VerificationCode": "Verification Code",
  "Description.SignupCompliance.TermsOfUse": "I have reviewed and agreed to the {termsOfUseLink}",
  "Description.SignupCompliance.PrivacyPolicyAck": "Acknowledge the {privacyPolicyLink}",
  "Description.VerifiedParentalConsentModal.EnterCodeNoEmailReveal":
    "Enter the code we just sent to your parent's email.",
  "Description.VerifiedParentalConsentModal.LegalCheckboxLabel":
    "By checking this box and clicking continue, you are giving consent to your child to access Roblox.",
  "Reponse.PasswordKISAComplexity":
    "A password containing a combination of uppercase and lowercase letter and number are required.",
  "Response.PasswordKISAComplexity":
    "A password containing a combination of uppercase and lowercase letter and number are required.",
  "Description.SignupOtpModal.LegalCheckboxLabel":
    "By checking the box and clicking continue, you are giving consent to your child to access Roblox.",
  "Action.Continue": "Continue",
  "Description.Try": "Try",
  "Heading.FinishAccountCreation": "Create Your Roblox Account",
  "Description.SelectBirthdate":
    "Start by entering your birthday. This helps confirm you're an adult. Later, you'll add parent privileges and link to your child's account. ",
  "Description.LoginWithEmail": "You can sign into your account anytime with your email address.",
  "Description.AccountSwitchSignupLogoutOtherAccounts":
    "By clicking Sign Up, you are acknowledging to log out of {startStylingTag}all your logged-in accounts{endStylingTag}.",
  "Header.ConfirmSignUp": "Confirm Sign Up",
  "Label.BirthdayRequired": "Birthday (Required)",
  "Label.ContinueOrExit": "Continue or Exit",
  "Description.ContinueChildRequest": "Continue to complete your child's request. ",
  "Action.ExitSetup": "Exit Setup",
  "Heading.CreateANewAccount": "Create A New Account",
  "Header.LogOutOfOtherAccounts": "Log Out of Other Accounts",
  "Description.LogoutConfirmation":
    "You’ll need to log out of your other Roblox accounts on this device before adding a new account\t",
  "Action.Logout": "Log Out",
  "Description.ParentLogoutConfirmation":
    "You’ll need to log out of your other Roblox accounts on this device before adding a new account with parent privileges",
  "Description.SignUpPage":
    "Sign up to make your Roblox account and enjoy millions of free experiences.",
  "Title.SignUpPage": "Sign Up - Roblox",
  "Heading.CannotSignUp": "Can't Sign Up",
  "Description.UnderAgeAlert": "You do not meet the minimum age requirement to play Roblox.",
  "Action.IUnderstand": "I Understand",
  "Description.VerificationPageMultiStep":
    "By clicking Continue, you are agreeing to the Terms of Use including the arbitration clause and you are acknowledging the Privacy Policy.",
  "Heading.UserGreetingWithName": "Hi {username}",
  "Label.OrCreateAPasskey": "Or create a passkey",
  "Description.Or": "OR",
  "Action.CreateAPasskey": "Create a passkey",
  "Title.LogOut": "Log Out",
  "Description.LogOutSignup": "To create a new account, first log out of your current session.",
  "Description.GuardianRequirement":
    "You must be a parent or legal guardian in order to manage a child’s account",
  "Label.BirthdayWithAge": "Birthday ({yearsOld} years old)",
  "Description.InvalidParentAccountLink":
    "This link is no longer valid. Click “Use existing account” from the email in your inbox to sign in with your email address. Otherwise, send another request from your child’s device.",
  "Title.InvalidLink": "Invalid link",
  "Label.Error.MinimumAge5": "New accounts must be above the age of five",
  "Header.CreatePasswordOrPasskey": "Hey {username}, create a password or passkey",
  "Description.SetAuthMethodHelp":
    "This ensures that you never lose access to your Roblox account.",
  "Label.MaybeTryOneOfThese": "Maybe try one of these",
  "Description.VerificationPage.CreateAccount":
    "By clicking Create Account, you are agreeing to the Terms of Use including the arbitration clause and you are acknowledging the Privacy Policy.",
  "Header.CreatePassword": "Hey {username}, create a password",
  "Label.NewPasswordError1": "Password should be at least 8 characters long",
  "Label.NewPasswordError2": "Password should not match username",
  "Label.NewPasswordError3": "It should not be a simple password",
  "Description.RobloxNotAvailableInRegion": "Roblox is temporarily unavailable in your region.",
  "Header.CreatePasskey": "Hey {username}, create a passkey",
  "Header.PleaseTryAgain": "Please Try Again",
  "Description.SelectBirthdateExpT1":
    "Start by entering your birthday. Later, to confirm you’re an adult, you’ll need to verify this birthday with a government ID, credit card, or by camera depending on your region.",
  "Description.VerificationLinkingText.VariableButtonName":
    "Your Roblox account will be linked to your account on {platform}. You can unlink from the Settings screen at any time. There may be a cool down before being able to link to another account on {platform}. By clicking {ctaButton}, you are agreeing to the Terms of Use including the arbitration clause and you are acknowledging the Privacy Policy.",
  "Description.ConsentClause.FullCopy":
    "I agree to Roblox’s Terms of Use (including arbitration) and acknowledge its Privacy Policy. If under 18, I agree that my parent/guardian permits me to create this account and agrees to the Terms of Use.",
  "Description.SignUpAgreement.FullCopy":
    "By clicking Sign Up, you are agreeing to our {termsOfUseLink} (including arbitration) and acknowledge our {privacyPolicyLink}. If you are under 18, you agree that your parent/guardian permits you to create this account and agrees to our Terms of Use.",
  "Description.SignUpAgreement.FullCopy.Continue":
    "By clicking Continue, you are agreeing to our Terms of Use (including arbitration) and acknowledge our Privacy Policy. If you are under 18, you agree that your parent/guardian permits you to create this account and agrees to our Terms of Use.",
  "Description.SignupAgreement.FullCopy.CreateAccount":
    "By clicking Create Account, you are agreeing to our Terms of Use (including arbitration) and acknowledge our Privacy Policy. If you are under 18, you agree that your parent/guardian permits you to create this account and agrees to our Terms of Use.",
  "Description.SignUpAgreement.ShortCopy":
    "I agree to Roblox’s Terms of Use (including arbitration) and acknowledge its Privacy Policy.",
  "Description.AgreeToTermsWithGuardian.NoParameters":
    "I agree to Roblox’s Terms of Use (including arbitration) and acknowledge its Privacy Policy.  If under 18, I agree that my parent/guardian permits me to create this account and agrees to the Terms of Use.",
  "Description.AgreeToTermsAndArb.NoParams":
    "I agree to Roblox’s Terms of Use (including arbitration) and acknowledge its Privacy Policy.",
  "Description.AgreeToTerms.NoParams":
    "I agree to Roblox’s Terms of Use and acknowledge its Privacy Policy.",
  "Description.AgreeToTermsWithGuardian":
    "I agree to Roblox’s {openTermsTag}Terms of Use{closeTermsTag} (including arbitration) and acknowledge its {openPrivacyTag}Privacy Policy{closePrivacyTag}.  If under 18, I agree that my parent/guardian permits me to create this account and agrees to the {openTermsTag}Terms of Use{closeTermsTag}.",
  "Description.AgreeToTerms":
    "I agree to Roblox’s {openTermsTag}Terms of Use{closeTermsTag} and acknowledge its {openPrivacyTag}Privacy Policy{closePrivacyTag}.",
  "Description.AgreeToTermsAndArb":
    "I agree to Roblox’s {openTermsTag}Terms of Use{closeTermsTag} (including arbitration) and acknowledge its {openPrivacyTag}Privacy Policy{closePrivacyTag}.",
  "Description.SignUpAgreement.FullCopy.CreateAccount":
    "By clicking Create Account, you are agreeing to our Terms of Use (including arbitration) and acknowledge our Privacy Policy. If you are under 18, you agree that your parent/guardian permits you to create this account and agrees to our Terms of Use.",
  "Description.SignUpAgreement.FullCopyCheckbox.WithParameters":
    "I agree to Roblox’s {termsOfUseLink} (including arbitration) and acknowledge its {privacyPolicyLink}.  If under 18, I agree that my parent/guardian permits me to create this account and agrees to the Terms of Use.",
  "Description.SignUpAgreement.ShortCopyCheckbox.WithParameters":
    "I agree to Roblox’s {termsOfUseLink} (including arbitration) and acknowledge its {privacyPolicyLink}.",
  PasswordErrorLength: "Is between 8 and 200 characters long",
  "Label.PasswordErrorLength": "Is between 8 and 200 characters long",
  "Label.PasswordErrorLengthNew": "Password should be between 8 and 200 characters long",
  "Label.PasswordErrorSimple": "Password should not be too simple",
  "Label.SignIn": "Sign In",
  "Description.SignUpAgreement.FullCopy.LinkParams":
    "By clicking Create Account, you are agreeing to our {termsOfUseLink} (including arbitration) and acknowledge our {privacyPolicyLink}. If you are under 18, you agree that your parent/guardian permits you to create this account and agrees to our Terms of Use.",
  "Description.SignUpAgreement.FullCopy.FullParams":
    "By clicking {buttonText}, you are agreeing to our {termsOfUseLink} (including arbitration) and acknowledge our {privacyPolicyLink}. If you are under 18, you agree that your parent/guardian permits you to create this account and agrees to our Terms of Use.",
  "Heading.DiscoverMillionsExperiences": "Discover over 30 million experiences",
  "Label.ShowPassword": "Show Password",
  "Label.HidePassword": "Hide Password",
  "Label.AlreadyHaveAccountSignIn": "Already have an account? {startTag}Sign in{endTag}",
  "Header.JumpBackIn": "Jump back into your experiences",
  "Heading.CreateANewAccountSentenceCase": "Create a new account",
  "Heading.ConfirmYourSelection": "Confirm your selection",
  "Body.SignupExitAlmostDone":
    "Are you sure you want to stop creating an account? You're almost done!",
  "Action.Yes": "Yes",
  "Heading.SignupHaveFunNoExclamation": "Sign up and start having fun",
  "Action.CreateAccountSentenceCase": "Create account",
  "Header.CreateAnAccount": "Create an account",
  "Label.SignInLowercase": "Sign in",
  "Heading.UserGreetingWithNameAndPasskeyPassword": "Hey {username}, create a passkey or password",
  "Description.SecureAccountWithPasskeyText":
    "Secure your account with a passkey to quickly sign-in with your phone in the future, or add a password for manual sign-in.",
  "Action.CreateAPassword": "Create a password",
  "Heading.ChooseSignIn": "We created your account. Choose how you’ll sign-in.",
  "Header.CreatedAccountChooseSignin": "We created your account. Choose how you'll sign-in.",
  "Description.CreateAccountPasskeyEmphasisDescription":
    "Passkeys allow you to sign in quickly with your Face ID, fingerprint, or the PIN you use to unlock your device.",
  "Label.EnterYourEmail": "Enter your email",
  EnterYourEmailCaps: "Enter your Email",
  "Action.AddAnEmail": "Add an email",
  "Action.AddAnEmailCaps": "Add an Email",
  "Label.EnterYourParentsEmail": "Enter your parent's email",
  "Label.EnterYourParentsEmailCaps": "Enter your parent's Email",
  "Action.AddYourParentsEmail": "Add your parent's email",
  "Action.AddYourParentsEmailCaps": "Add your parent's Email",
  "Label.EnterParentalEmail": "Enter your parental recovery email",
  "Action.AddParentalEmail": "Add your parental recovery email",
  "Description.CreatePasskeyOrOTP":
    "Create a passkey for your Roblox account or add an email to sign in with a one time password.",
  "Label.ExampleEmail": "example@email.com",
  "Action.EnableFaceId": "Enable Face ID",
  "Description.FaceIdPromo": "Face ID is the most secure and easiest way to sign in on Roblox.",
  "Action.SetupLater": "Setup later",
  "Label.EnterEmailForOTPO13": "Enter your email to sign in with a one-time passcode",
  "Label.EnterEmailForOTPU13":
    "Enter your parent’s email to sign in with a one-time passcode and support account recovery",
  "Action.Download": "Download",
  "Header.PageTitle": "One platform.{lineBreak}Millions of games.",
  "Description.PageHeaderDescription":
    "Play immersive games, watch interactive clips, chat with friends, and build worlds of your own.",
  "Title.GamesToGetYouStarted": "Games to get you started",
  "Action.Create": "Create",
  "Description.SignUpAgreement.CreateAnAccount":
    "By creating an account, you agree to our {startTermsTag}Terms{endTermsTag}, including arbitration, and acknowledge our {startPrivacyTag}Privacy Policy{endPrivacyTag}. If you’re under 18, your parent or guardian must permit your account and agree to our Terms.",
  "Label.EmailOptional.Short": "Email (optional)",
  "Description.ChooseHowYouSignIn": "Choose how you sign in to Roblox",
  "Action.CreatePassword": "Create password",
  "Label.PasswordError3.V2": "Isn't a simple password",
  "Label.PasswordError2.V2": "Doesn't match username",
  "Description.EmailHint": "Enter date",
  "Description.BirthdayHint": "Enter date",
  "Heading.PlayCreateConnect": "Play, create, and connect with millions of players.",
  "Label.AddPassword": "Add password",
  "Description.CreateAccountAgreement":
    "By creating an account, you agree to our Terms, including arbitration, and acknowledge our Privacy Policy. If you’re under 18, your parent or guardian must permit your account and agree to our Terms."
};
window.Roblox &&
  window.Roblox.BundleDetector &&
  window.Roblox.BundleDetector.bundleDetected(
    "DynamicLocalizationResourceScript_Authentication.SignUp"
  );
