var Roblox = Roblox || {};
Roblox.LangDynamic = Roblox.LangDynamic || {};
Roblox.LangDynamic["Feature.Home"] = {
  LabelGreeting: "Hello, {username}!",
  HeadingFriends: "Friends ({friendCount})",
  HeadingRecentlyPlayed: "Recently Visited",
  HeadingMyFavorites: "My Favorites",
  HeadingMyFeed: "My Feed",
  HeadingFriendActivity: "Friend Activity",
  HeadingBlogNews: "Blog News",
  HeadingDeveloperExchange: "Developer Exchange",
  LabelCreateEarn: "Create experiences, earn money",
  LabelAnnouncement: "Announcement",
  ActionSeeAll: "See All",
  ActionSeeMore: "See More",
  ActionLearnMore: "Learn More",
  ActionShare: "Share",
  ActionWhatAreYouUpto: "What are you up to?",
  LabelStatusUpdateFailed: "Status update failed.",
  LabelSharing: "Sharing...",
  ResponseErrorNoLogin: "Please log into your account.",
  ResponseErrorNoBlank: "Update cannot be blank. Please try again.",
  ResponseErrorTooManyUpdates: "Too many updates. Please try again later.",
  ResponseErrorOther: "System issue. Please try again later, then contact Support.",
  HeadingFriendsTitle: "Friends",
  "Label.FindMyFeed": "Looking for My Feed? It's now on the side menu",
  "Action.BackToTop": "Back To Top",
  "Action.CheckItOut": "Check It Out!",
  "Heading.NewWindowsApp": "New Windows Roblox App!",
  "Description.WindowsAppIntro":
    "Find new experiences, visit with friends, customize your avatar, and more with the new seamless desktop app!",
  "Action.TryItNow": "Try It Now",
  "Heading.NewWindowsAppBeta": "Try the Roblox Windows App Beta!",
  "Label.TopicFightingAndBattle": "Fighting & Battle",
  "Label.TopicSurvival": "Survival",
  "Label.TopicShooter": "Shooter",
  "Label.TopicRacing": "Racing",
  "Label.TopicChildhoodGames": "Childhood games",
  "Label.Topic1vsALL": "1 vs ALL",
  "Label.TopicMurderMystery": "Murder Mystery",
  "Label.TopicRhythmicAction": "Rhythmic Action",
  "Label.TopicHorror": "Horror",
  "Label.TopicAdventureQuest": "Adventure Quest",
  "Label.TopicAdvertureAndExploration": "Adventure & Exploration",
  "Label.TopicScavengerHunt": "Scavenger Hunt",
  "Label.TopicAdventureStories": "Adventure Stories",
  "Label.TopicMMORPG": "MMORPG",
  "Label.TopicDressUp": "Dress Up",
  "Label.TopicRole": "Role",
  "Label.TopicMorph": "Morph",
  "Label.TopicVirtualReality": "Virtual Reality",
  "Label.TopicAnimals": "Animals",
  "Label.TopicPhysics": "Physics",
  "Label.TopicVehicleSimulation": "Vehicle Simulation",
  "Label.TopicRealLifeRoleplay": "Real life Roleplay",
  "Label.TopicRealTimeStrategy": "Realtime Strategy",
  "Label.TopicTowerDefense": "Tower Defense",
  "Label.TopicIndividualSports": "Individual Sports",
  "Label.TopicTeamSports": "Team Sports",
  "Label.TopicShowcase": "Showcase",
  "Label.TopicSlides": "Slides",
  "Label.TopicCartRides": "Cart rides",
  "Label.TopicSurvivalMinigames": "Survival minigames",
  "Label.TopicTycoonAndStrategy": "Tycoon & Strategy",
  "Label.TopicCooperativeTycoons": "Cooperative Tycoons",
  "Label.TopicFreeAdmin": "Free Admin",
  "Label.TopicSocialVibe": "Social Vibe",
  "Label.TopicPlatformerObby": "Platformer Obby",
  "Label.TopicSpeedrun": "Speedrun",
  "Label.TopicClickerSimulator": "Clicker Simulator",
  "Label.TopicCollectorSimulator": "Collector Simulator",
  "Label.TopicHomestore": "Homestore",
  "Label.TopicTryOnShopping": "Try on Shopping",
  "Label.TopicBuildInSandbox": "Build in Sandbox",
  "Label.TopicFreePlays": "Free Visits",
  "Label.TopicMediaAndPhoto": "Media and Photo",
  "Label.TopicFilms": "Films",
  "Label.TopicAnimation": "Animation",
  "Label.TopicCardGames": "Card Games",
  "Label.TopicBoardGames": "Board Games",
  "Label.TopicDraw": "Draw",
  "Label.TopicQuiz": "Quiz",
  "Label.TopicEscapeRoom": "Escape Room",
  "Label.TopicTraditionalPuzzles": "Traditional Puzzles",
  "Label.TopicOther": "Other",
  "Label.TopicAction": "Action",
  "Label.TopicAdventure": "Adventure",
  "Label.TopicSimulation": "Simulation",
  "Label.TopicStrategy": "Strategy",
  "Label.TopicSports": "Sports",
  "Label.TopicIdle": "Idle",
  "Label.TopicMinigames": "Minigames",
  "Label.TopicTycoon": "Tycoon",
  "Label.TopicSocialHangout": "Social Hangout",
  "Label.TopicPlatformer": "Platformer",
  "Label.TopicSimulator": "Simulator",
  "Label.TopicShopping": "Shopping",
  "Label.TopicSandbox": "Sandbox",
  "Label.TopicMediaCreation": "Media Creation",
  "Label.TopicTabletopGames": "Tabletop Experiences",
  "Label.TopicPuzzle": "Puzzle",
  "Label.TopicRolePlaying": "Role-playing",
  "Label.TopicRealWorldRoleplay": "Real World Roleplay",
  "Label.TopicRealWorldSimulation": "Real World Simulation",
  "Heading.NewMacAppBeta": "Try the Roblox Mac App Beta!",
  "Label.TopicChallenge": "Challenge",
  "Label.TopicAvatarsForYou": "Avatar Items for you",
  "Label.TopicHubs": "Hubs",
  "Label.TopicHalloween": "Halloween",
  "Label.AvatarItemsForYou": "Avatar Items For You",
  "Label.TopicBasedOnYourInterests": "Based on your past interests",
  "Label.TopicSponsoredGames": "Sponsored",
  "Label.TopicPeopleYouMayKnow": "People You May Know",
  "Heading.JoinYourFriends": "Join Your Friends",
  "Heading.FriendVisited": "Friend Visited",
  HeadingFriendSingular: "Friend",
  HeadingFriendPlural: "Friends",
  XFriendsVisited: "{friendCount} friends visited",
  NFriendsVisited:
    "{friendCount, plural, =0 {# friend visited} =1 {# friend visited} other {# friends visited}}",
  SingularFriendVisited: "1 friend visited",
  PluralFriendsVisited: "{friendCount} friends visited",
  SingularFriend: "1 Friend",
  PluralFriend: "{friendCount} Friends",
  PluralFriendsVisitedUpperCase: "{friendCount} Friends Visited",
  SingularFriendVisitedUpperCase: "1 Friend Visited",
  NFriendsVisitedUpperCase:
    "{friendCount, plural, =0 {# Friend Visited} =1 {# Friend Visited} other {# Friends Visited}}",
  SingularFriendVisitedSentenceCase: "1 Friend visited",
  PluralFriendsVisitedSentenceCase: "{friendCount} Friends visited",
  NFriendsVisitedSentenceCase:
    "{friendCount, plural, =0 {No friend visited} =1 {# Friend visited} other {# Friends visited}}",
  LabelMoreToExplore: "More To Explore",
  LabelGetStartedOnRoblox: "Get Started On Roblox",
  LabelYouMightAlsoLike: "You Might Also Like",
  "Experiment.Reminders.BodyShared":
    "Recently, your account violated Roblox’s rules about {policy_violation}.",
  "Experiment.Reminders.Title": "Remember our Community Guidelines",
  "Experiment.Reminders.BodyPositiveVariant":
    "Remember to keep Roblox safe and fun for everyone. Play fair, and treat other players with respect.",
  "Experiment.Reminders.BodyWarningVariant":
    "Follow the rules in the Community Standards. If you don't, your account will receive more warnings or suspensions.",
  "Experiment.Reminders.Button": "I understand",
  "Experiment.Reminders.ViolationSexualContent": "Sexual Content",
  "Experiment.Reminders.ViolationIrlDangerousActivities":
    "Suicide, Self Injury, and Harmful Behavior.",
  "Experiment.Reminders.ViolationAskingForPII": "Sharing Personal Information",
  "Experiment.Reminders.ViolationBullyingAndHarassment": "Bullying and Harassment",
  "Experiment.Reminders.ViolationDiscriminationAndHate": "Discrimination and Hate",
  "Experiment.Reminders.ViolationViolentContentAndGore": "Violent Content and Gore",
  "Experiment.Reminders.ViolationIllegalAndRegulatedGoodsAndActivities":
    "Illegal and Regulated Goods and Activities",
  "Experiment.Reminders.ViolationRomanticContent": "Romantic Content",
  "Experiment.Reminders.ViolationProfanity": "Profanity",
  "Experiment.Reminders.ViolationMisleadingImpersonationMisrepresentation":
    "Bullying and Harassment",
  "Experiment.Reminders.ViolationPoliticalContent": "Political Content",
  "Experiment.Reminders.ViolationExtortionAndBlackmail": "Threats, Bullying and Harassment",
  "Experiment.Reminders.ViolationScams": "Scams",
  "Experiment.Reminders.ViolationSpam": "Spam",
  "Experiment.Reminders.ViolationDirectingUsersOffPlatform": "Directing Users Off-Platform",
  "Experiment.Reminders.ViolationDisruptiveAudio": "Misusing Roblox Systems",
  "Experiment.Reminders.ViolationCheatingAndExploiting": "Cheating",
  "Experiment.Reminders.ViolationDmca": "Intellectual Property Violations",
  "Experiment.Reminders.ViolationMisusingRobloxSystems": "Misusing Roblox Systems",
  "Experiment.Reminders.ViolationRobloxEconomy": "Roblox Economy Violations",
  "Experiment.Reminders.ViolationAdvertising": "Prohibited Advertising Practices and Content",
  "Experiment.Reminders.ViolationRealWorldTragedy": "Real-World Sensitive Events",
  "Experiment.Reminders.ViolationIpViolation": "Intellectual Property Violations",
  "Experiment.Reminders.ViolationEncouragingDangerousBehavior":
    "Suicide, Self Injury, and Harmful Behavior",
  "Experiment.Reminders.ViolationContestsAndSweepstakes":
    "Illegal / Regulated Goods and Activities",
  "Experiment.Reminders.ViolationSharingYourOwnPii": "Sharing Personal Information",
  "Experiment.Reminders.ViolationOffPlatformSpeechAndBehavior":
    "Harmful Off-Platform Speech and Behavior",
  "Experiment.Reminders.ViolationThreatsOrAbuseOfRobloxEmployeesOrAffiliates":
    "Threats, Bullying, and Harassment",
  "Experiment.Reminders.ViolationTerrorismExtremism": "Terrorism and Violent Extremism",
  "Experiment.Reminders.ViolationTrademark": "Intellectual Property Violations",
  "Experiment.Reminders.ViolationVirtualCasino": "Virtual Casino",
  "Experiment.Reminders.ViolationPoliticalContent.V2": "Political Figures and Entities",
  "Label.PaidAccess": "Paid Access",
  "Label.ActionRpg": "Action RPG",
  "Label.ColoringAndDrawing": "Coloring & Drawing",
  "Label.Adventure": "Adventure",
  "Label.AnimalSim": "Animal Sim",
  "Label.AvatarShopping": "Avatar Shopping",
  "Label.BattlegroundsAndFighting": "Battlegrounds & Fighting",
  "Label.Minigame": "Minigame",
  "Label.BattleRoyaleShooter": "Battle Royale",
  "Label.BoardAndCardGames": "Board & Card Games",
  "Label.ChildhoodGame": "Childhood Game",
  "Label.ClassicObby": "Classic Obby",
  "Label.Communication": "Communication",
  "Label.ContentSharing": "Content Sharing",
  "Label.DeathmatchShooter": "Deathmatch Shooter",
  "Label.DressUp": "Dress Up",
  "Label.Education": "Education",
  "Label.Entertainment": "Entertainment",
  "Label.Escape": "Escape",
  "Label.EscapeRoom": "Escape Room",
  "Label.Exploration": "Exploration",
  "Label.Game": "Game",
  "Label.Hangout": "Hangout",
  "Label.Idle": "Idle",
  "Label.IncrementalSimulator": "Incremental Simulator",
  "Label.Life": "Life",
  "Label.MatchAndMerge": "Match & Merge",
  "Label.MorphRoleplay": "Morph Roleplay",
  "Label.MusicAndAudio": "Music & Audio",
  "Label.MusicAndRhythm": "Music & Rhythm",
  "Label.ObbyAndPlatformer": "Obby & Platformer",
  "Label.NA": "N/A",
  "Label.OneVsAll": "1 vs All",
  "Label.OpenWorldAction": "Open World Action",
  "Label.OpenWorldAndSurvivalRpg": "Open World & Survival RPG",
  "Label.OtherAction": "Other Action",
  "Label.OtherAdventure": "Other Adventure",
  "Label.OtherEntertainment": "Other Entertainment",
  "Label.OtherObbyAndPlatformer": "Other Obby & Platformer",
  "Label.OtherPartyAndCasual": "Other Party & Casual",
  "Label.OtherPuzzle": "Other Puzzle",
  "Label.OtherRoleplayAndAvatarSim": "Other Roleplay & Avatar Sim",
  "Label.OtherRpg": "Other RPG",
  "Label.OtherShooter": "Other Shooter",
  "Label.OtherShopping": "Other Shopping",
  "Label.OtherSimulation": "Other Simulation",
  "Label.OtherSocial": "Other Social",
  "Label.Sandbox": "Sandbox",
  "Label.OtherSportsAndRacing": "Other Sports & Racing",
  "Label.OtherStrategy": "Other Strategy",
  "Label.OtherSurvival": "Other Survival",
  "Label.PartyAndCasual": "Party & Casual",
  "Label.PetCare": "Pet Care",
  "Label.PhysicsSim": "Physics Sim",
  "Label.Puzzle": "Puzzle",
  "Label.PveShooter": "PvE Shooter",
  "Label.Quiz": "Quiz",
  "Label.RoleplayAndAvatarSim": "Roleplay & Avatar Sim",
  "Label.Rpg": "RPG",
  "Label.Runner": "Runner",
  "Label.ScavengerHunt": "Scavenger Hunt",
  "Label.Shooter": "Shooter",
  "Label.Shopping": "Shopping",
  "Label.ShowcaseAndHub": "Showcase & Hub",
  "Label.Simulation": "Simulation",
  "Label.Social": "Social",
  "Label.SportsAndRacing": "Sports & Racing",
  "Label.Story": "Story",
  "Label.Strategy": "Strategy",
  "Label.Survival": "Survival",
  "Label.TowerDefense": "Tower Defense",
  "Label.TowerObby": "Tower Obby",
  "Label.TurnBasedRpg": "Turn-based RPG",
  "Label.Tycoon": "Tycoon",
  "Label.UtilityAndOther": "Utility & Other",
  "Label.VehicleSim": "Vehicle Sim",
  "Label.Video": "Video",
  "Label.Word": "Word",
  "Label.Connection": "Connection",
  "ClientCacheFallbackBanner.Label.Error": "Error",
  "Action.Refresh": "Refresh",
  "Label.RefreshPageToLoadContents": "Refresh page to load contents",
  "Action.OpenMenu": "Open Menu",
  "ClientCacheFallbackBanner.Label.ErrorRefreshingToastTitle": "Please try again",
  "ClientCacheFallbackBanner.Label.ErrorRefreshingToastSubtitle": "Please try again later",
  "ClientCacheFallbackBanner.Label.RefreshPageToLoadContents": "Refresh page to load contents",
  "ClientCacheFallbackBanner.Action.Refresh": "Refresh",
  BecauseYouPlayedX: "Because you played {ExperienceName}",
  "Label.GameItemsSubtitle": "Enhance play with these recommended items",
  "Experiment.TextFilterEducation.Kids.Title.Warning": "Your chat could go away",
  "Experiment.TextFilterEducation.General.Body.Romance.Modified":
    "To avoid losing access to chat, stay away from romance or dating.",
  "Experiment.TextFilterEducation.Kids.Title.Modified":
    "We had to change or block some of your messages",
  "Experiment.TextFilterEducation.Kids.Body.Respect": "Remember: Always use kind words.",
  "Experiment.TextFilterEducation.Kids.Body.Spam": "Remember: Send each message only once.",
  "Experiment.TextFilterEducation.Kids.Body.Pii":
    "Remember: keep your name, school, and where you live to yourself.",
  "Experiment.TextFilterEducation.General.Title.Modified":
    "We had to change or block some of your recent messages",
  "Experiment.TextFilterEducation.General.Title.Warning": "You’re close to losing chat",
  "Experiment.TextFilterEducation.General.Body.Respect.Modified":
    "To avoid losing access to chat, always keep messages respectful.",
  "Experiment.TextFilterEducation.General.Body.Respect.Warning":
    "We had to change or block some of your messages. Remember: always keep messages respectful.",
  "Experiment.TextFilterEducation.General.Body.Spam.Modified":
    "To avoid losing access to chat, send each message only once.",
  "Experiment.TextFilterEducation.General.Body.Spam.Warning":
    "We had to change or block some of your messages. Remember: send each message only once.",
  "Experiment.TextFilterEducation.General.Body.Pii.Modified":
    "To avoid losing access to chat, keep your personal info to yourself.",
  "Experiment.TextFilterEducation.General.Body.Pii.Warning":
    "We had to change or block some of your messages. Remember: keep your personal info to yourself.",
  "Experiment.TextFilterEducation.General.Body.Romance.Warning":
    "We had to change or block some of your messages. Remember: stay away from romance or dating."
};
window.Roblox &&
  window.Roblox.BundleDetector &&
  window.Roblox.BundleDetector.bundleDetected("DynamicLocalizationResourceScript_Feature.Home");
