var Roblox = Roblox || {};
Roblox.LangDynamic = Roblox.LangDynamic || {};
Roblox.LangDynamic["Feature.Catalog"] = {
  "Heading.CatalogPage": "Catalog",
  "Heading.CatalogCategory": "Category",
  "Label.BreadCrumb.Free": "Free",
  "Label.BreadCrumb.Group": "Community:",
  "Label.BreadCrumb.PriceAbove": "{price} and above",
  "Label.BreadCrumb.PriceBelow": "{price} and below",
  "Label.BreadCrumb.ResultsCount": "{startNumber} - {endNumber} of {resultsCount} Results",
  "Label.BreadCrumb.GenreOrText": "{genreName1} or {genreName2}",
  "Label.BreadCrumb.GenreSelectedText": "Genre: {genreCount} selected",
  "Label.AllFeaturedItems": "View All Featured Items",
  "Label.FeaturedItemsOnRoblox": "Featured Items on {spanStart}{roblox}{spanEnd}",
  "Label.CategoryAttributes": "Attributes",
  "Label.CategoryType": "Type",
  "Label.AllGenres": "All Genres",
  "Label.Card.Remaining": "Remaining:",
  "Label.SearchField": "Search",
  "Label.Card.PriceWas": "Was",
  "Label.Card.CreatorBy": "By",
  "Label.Username": "Username",
  "Label.Filter.Category": "Category",
  "Label.Filter.Filter": "Filter",
  "Label.Filter.Filters": "Filters",
  "Label.Filter.Sorting": "Sorting",
  "Label.Filter.Price": "Price",
  "Label.Filter.Creator": "Creator",
  "Label.Filter.Genre": "Genre",
  "Label.Filter.ByTime": "By Time",
  "Label.Filter.PriceMin": "Min",
  "Label.Filter.PriceTo": "To",
  "Label.Filter.PriceMax": "Max",
  "Label.Filter.Hide": "Hide",
  "Label.Filter.Show": "Show",
  "Label.Filter.UnavailableItems": "Unavailable Items",
  "Response.Error.Filter": "Errors exist in Filter tab",
  "Action.BuyRobux": "Buy Robux",
  "Action.Go": "Go",
  "Action.Filter.Cancel": "Cancel",
  "Action.Filter.Apply": "Apply",
  "Action.ViewAllItems": "View All Items",
  "Label.Dialog.AddGearTitle": "Add Gear to Your Experience",
  "Description.Dialog.AddGearBody":
    "To add gear to your experience, find an item in the catalog and click the Add to Experience button. The item will automatically be allowed in experience, and you'll receive a commission on every copy sold from your experience page. (You can only add gear that's for sale.)",
  "Action.Dialog.AddGearOk": "OK",
  "Response.NoItemsFound": "No items found.",
  "Response.NoSaleItemsFromSearch":
    "Your search did not find items for sale. Unavailable items displayed below.",
  "Response.TemporarilyUnavailable": "Catalog temporarily unavailable. Please try again later.",
  "Response.GenericError": "An error occurred. Please try again later.",
  LabelAll: "All",
  LabelAllCategories: "All Categories",
  LabelFeatured: "Featured",
  LabelBodyParts: "Body Parts",
  LabelClothing: "Clothing",
  LabelCollectibles: "Collectibles",
  LabelGear: "Gear",
  LabelAccessories: "Accessories",
  LabelAnimations: "Animations",
  LabelAvatarAnimations: "Avatar Animations",
  LabelAllClothing: "All Clothing",
  LabelShirts: "Shirts",
  LabelTShirts: "T-Shirts",
  LabelPants: "Pants",
  LabelPackages: "Packages",
  LabelAllBodyParts: "All Body Parts",
  LabelHeads: "Heads",
  LabelFaces: "Faces",
  LabelAllFeatured: "All Featured Items",
  LabelFeaturedAccesories: "Featured Accessories",
  LabelFeaturedAnimations: "Featured Animations",
  LabelFeaturedFaces: "Featured Faces",
  LabelFeaturedGear: "Featured Gear",
  LabelFeaturedPackages: "Featured Packages",
  LabelAllCollectibles: "All Collectibles",
  LabelCollectibleAccessories: "Collectible Accessories",
  LabelCollectibleFaces: "Collectible Faces",
  LabelCollectibleGear: "Collectible Gear",
  LabelAccessoryAll: "All Accessories",
  LabelAccessoryHats: "Hats",
  LabelAccessoryHair: "Hair",
  LabelAccessoryFace: "Face",
  LabelAccessoryNeck: "Neck",
  LabelAccessoryShoulder: "Shoulder",
  LabelAccessoryFront: "Front",
  LabelAccessoryBack: "Back",
  LabelAccessoryWaist: "Waist",
  LabelRelevance: "Relevance",
  LabelMostFavorited: "Most Favorited",
  LabelBestselling: "Bestselling",
  LabelRecentlyUpdated: "Recently Updated",
  LabelPriceHighFirst: "Price (High to Low)",
  LabelPriceLowFirst: "Price (Low to High)",
  LabelGearAll: "All Gear",
  LabelGearBuilding: "Building",
  LabelGearExplosive: "Explosive",
  LabelGearMelee: "Melee",
  LabelGearMusical: "Musical",
  LabelGearNavigation: "Navigation",
  LabelGearPowerUps: "Power Up",
  LabelGearRanged: "Ranged",
  LabelGearSocial: "Social",
  LabelGearPersonalTransport: "Transport",
  LabelGenreAll: "All Genres",
  LabelGenreBuilding: "Building",
  LabelGenreHorror: "Horror",
  LabelGenreTownAndCity: "Town and City",
  LabelGenreMilitary: "Military",
  LabelGenreComedy: "Comedy",
  LabelGenreMedieval: "Medieval",
  LabelGenreAdventure: "Adventure",
  LabelGenreSciFi: "Sci-Fi",
  LabelGenreNaval: "Naval",
  LabelGenreFPS: "FPS",
  LabelGenreRPG: "RPG",
  LabelGenreSports: "Sports",
  LabelGenreFighting: "Fighting",
  LabelGenreWestern: "Western",
  LabelAllCreators: "All Creators",
  LabelRoblox: "Roblox",
  LabelRobux: "Robux",
  LabelAllCurrency: "All Currency",
  LabelFree: "Free",
  LabelAnyPrice: "Any Price",
  LabelAllTime: "All Time",
  LabelPastWeek: "Past Week",
  LabelPastDay: "Past Day",
  LabelNoResellers: "No Resellers",
  "Label.Xbox": "Xbox",
  "Label.Amazon": "Amazon",
  "Label.GoogleOnly": "Google Only",
  "Label.Mobile": "Mobile",
  "Label.Ios": "iOS",
  "Label.Sale": "Sale",
  "Label.New": "New",
  "Label.Bundles": "Bundles",
  "Label.Bundle": "Bundle",
  "Label.FeaturedBundles": "Featured Bundles",
  "Label.Rthro": "Rthro",
  "Label.Favorites": "Favorites",
  "Label.FeaturedEmotes": "Featured Emotes",
  "Label.Emotes": "Emotes",
  "Label.Character": "Character",
  "Label.Body": "Body",
  "Label.Animation": "Animation",
  "Label.Face": "Face",
  "Label.Head": "Head",
  "Label.Hair": "Hair",
  "Label.Gear": "Gear",
  "Label.Limited": "Limited",
  "Label.SeeAll": "See All",
  "Label.ByCreatorLink": "By {linkStart}{creator}{linkEnd}",
  "Label.CommunityCreations": " Community Creations",
  LabelGenreTutorial: "Building",
  LabelGenreScary: "Horror",
  LabelGenreWar: "Military",
  LabelGenreFunny: "Comedy",
  LabelGenrePirate: "Naval",
  LabelGenreFantasy: "Medieval",
  LabelGenreWildWest: "Western",
  LabelGenreNinja: "Fighting",
  "Response.Throttled": "You're going too fast! Try again in a minute.",
  "Action.Sell": "Sell",
  "Label.OnSale": "On Sale",
  "Label.OriginalPrice": "Original Price",
  "Label.AveragePrice": "Average Price",
  "Label.SellCut": "You Earn:",
  "Label.MinimumAmount": "Minimum amount must be over 0.",
  "Action.Buy": "Buy",
  "Label.RobuxFee": "After {feePercentage}% Fee:",
  "Heading.BuyItem": "Buy Item",
  "Action.Cancel": "Cancel",
  "Action.Report": "Report",
  "Action.Remove": "Remove",
  "Heading.SellItem": "Sell Item",
  "Heading.Resellers": "Resellers",
  "Label.Characters": "Characters",
  "Label.Get": "Get",
  "Action.Rent": "Rent",
  "Label.TShirt": "T-Shirt",
  "Label.Emote": "Emote",
  "Label.Clothing": "Clothing",
  "Label.SellPageUpsell": "Selling is only available to users with a Roblox Plus membership.",
  "Label.AllCommunityCreations": "All Creations",
  "Heading.AvatarShop": "Avatar Shop",
  "Label.Premium": "Premium",
  "Label.Tops": "Tops",
  "Label.AllPremiumItems": "All Premium Items",
  "Label.PremiumOnly": "Available for Premium users only",
  "Label.ReportItem": "Report Item",
  "Label.Recommended": "Recommended",
  "Label.RecommendedItemsForYou": "Recommended Items for You",
  "Action.ViewFeaturedItems": "View Featured Items",
  LabelAllAvatarAnimations: "All Animations",
  "Response.PlacedOnSaleFailure": "Failed to place on sale",
  "Response.PlacedOnSaleSuccess": "Successfully placed on sale",
  "Response.TakenOffSaleFailure": "Failed to take off sale",
  "Response.TakenOffSaleSuccess": "Successfully taken off sale",
  "Label.AccessoryHead": "Head",
  "Label.Clothing.ShirtAccessories": "Shirts",
  "Label.Clothing.TShirtAccessories": "T-Shirts",
  "Label.Clothing.SweaterAccessories": "Sweaters",
  "Label.Clothing.JacketAccessories": "Jackets",
  "Label.Clothing.PantsAccessories": "Pants",
  "Label.Clothing.DressSkirtAccessories": "Dresses & Skirts",
  "Label.Clothing.ShortsAccessories": "Shorts",
  "Label.Clothing.ShoesBundles": "Shoes",
  "Label.Clothing.ClassicShirts": "Classic Shirts",
  "Label.Clothing.ClassicTShirts": "Classic T-Shirts",
  "Label.Clothing.ClassicPants": "Classic Pants",
  "Label.ComingSoon": "Coming soon! Check back later.",
  "Label.NotAvailable": "This item is not available at this time",
  "Label.AppleOnly": "Apple Only",
  "Label.TryOn": "Try On",
  "Label.TakeOff": "Take Off",
  "Label.3D": "3D",
  "Label.2D": "2D",
  "Label.AllItemsOnRoblox": "All Items on {spanStart}{roblox}{spanEnd}",
  "Label.Eyebrow": "Eyebrow",
  "Label.Eyelash": "Eyelash",
  LabelLiveHeads: "Live Heads",
  LabelClassicHeads: "Classic Heads",
  LabelClassicFaces: "Classic Faces",
  LabelAllHeads: "All Heads",
  "Heading.BuyItWith": "Buy it with",
  "Label.Total": "Total:",
  "Label.AllItems": "All Items",
  "Label.Filter.SortBy": "Sort By",
  "Label.Filter.SalesType": "Sales Type",
  "Label.Filter.Sorts": "Sorts",
  "Label.NewCollectibles": "New Collectibles!",
  "Message.CollectiblesInfo":
    "Collectible items can be resold from user to user after a holding period, even if the original stock is not sold out. Roblox Plus subscribers can list Collectible items for resale.",
  "Label.LimitedU": "Limited U",
  "Label.Unlimited": "Unlimited",
  "Heading.SellYourCollectibleItem": "Sell Your Collectible Item",
  "Label.PriceMinimum1": "Price (minimum 1)",
  "Label.MarketplaceFee30Percent": "Marketplace fee (at 30%)",
  "Label.YouGet": "You get",
  "Action.SellNow": "Sell Now",
  "Heading.TakeOffSale": "Take Off Sale",
  "Label.TakeOffSaleConfirmation": "Are you sure you want to take the item off sale?",
  "Heading.AddToProfile": "Add to Profile",
  "Heading.RemoveFromProfile": "Remove from Profile",
  "Response.AddedToProfile": "Added to your profile",
  "Response.RemovedFromProfile": "Removed from your profile",
  "Label.Trending": "Trending",
  "Label.InvalidPrice": "Price is invalid",
  "Label.SerialNumber": "Serial Number",
  "Action.AddToCart": "Add to cart",
  "Action.RemoveFromCart": "Remove from cart",
  "Action.Add": "Add",
  "Label.ShoppingCart": "Shopping cart",
  "Label.TotalUnformatted": "Total",
  "Message.Processing": "Processing",
  "Message.Unavailable": "Unavailable",
  "Heading.ItemAddedToCart": "{itemName} has been added to your cart",
  "Heading.ItemRemovedFromCart": "{itemName} has been removed from your cart",
  "Heading.CartLimitFailure": "Add to cart failed, you reached the {itemLimit} item limit",
  "Heading.CartFailure": "Add to cart failed, please try again later",
  "Heading.CartRemoveFailure": "Remove from cart failed, please try again later",
  "Heading.CartAddFailure": "Add to cart failed, please try again later",
  "Action.BuyCartItems": "Buy cart items",
  "Message.InsufficientFundsForTransaction": "You have insufficient funds for this transaction",
  "Label.AveragePriceColon": "Average Price:",
  "Label.SerialNumberColon": "Serial Number:",
  "Heading.SetPrice": "Set Price",
  "Heading.ItemInfo": "Item Info",
  "Heading.Overview": "Overview",
  "Label.RecentlyCreated": "Recently Created",
  "Label.ResaleFeePolicy": "Resale Fee Policy",
  "Message.ResaleFeePolicy":
    "The revenue from all Marketplace transactions, including resales, is shared between Roblox and the users involved in the transaction. For resales, this means that when a user accepts your price, {yourSharePercent}% of the Robux they pay will go to you as the reseller. The other {robloxFeePercent}% will go to Roblox and other users including the item creator.",
  "Label.ItemOwned": "Item Owned",
  "Action.GotIt": "Got It",
  "Label.ItemOwnedCount": "Owned Items ({itemCount})",
  "Label.BuyPrice": "Buy Price:",
  "Label.Holding": "Holding",
  "Label.OffSale": "Off Sale",
  "Label.ItemInAHold": "Item in a hold?",
  "Heading.HoldingPolicy": "Holding Policy",
  "Message.HoldingPolicy":
    "After purchasing, original sales enter a hold for up to 30 days. The item can only be resold after this holding period ends and resales will have a hold of up to 7 days. Only premium users can resell items.",
  "Heading.OffSaleItem": "Off Sale Item",
  "Label.Genres": "Genres",
  "Label.Tags": "Tags",
  "Label.Updated": "Updated",
  "Label.Description": "Description",
  "Action.ReadMore": "Read More",
  "Action.BuyNow": "Buy Now",
  "Message.RemainingBalance": "Your balance after this transaction will be {remainingBalance}.",
  "Message.ItemInInventory": "This item is available in your inventory.",
  "Label.BestPrice": "Best Price",
  "Action.SeeMoreReseller": "See More {linkStart}{resellerLink}{linkEnd}",
  "Action.Wear": "Wear",
  "Message.BundlePurchase":
    'Would you like to buy the "{bundleName}" from {sellerName} for {price}?',
  "Message.AssetPurchase":
    'Would you like to buy the {itemType} "{itemName}" from {sellerName} for {price}?',
  "Message.AssetGet":
    'Would you like to get the {itemType} "{itemName}" from {sellerName} for {price}?',
  "Label.Accessory": "Accessory",
  "Label.LeftArm": "Left Arm",
  "Label.LeftLeg": "Left Leg",
  "Label.RightArm": "RightArm",
  "Label.RightLeg": "Right Leg",
  "Label.ClassicShirt": "Classic Shirt",
  "Label.ClassicTShirt": "Classic T-Shirt",
  "Label.Torso": "Torso",
  "Label.ClimbAnimation": "Climb Animation",
  "Label.DeathAnimation": "Death Animation",
  "Label.FallAnimation": "Fall Animation",
  "Label.IdleAnimation": "Idle Animation",
  "Label.RunAnimation": "Run Animation",
  "Label.JumpAnimation": "Jump Animation",
  "Label.SwimAnimation": "Swim Animation",
  "Label.WalkAnimation": "Walk Animation",
  "Label.PoseAnimation": "Pose Animation",
  "Label.EmoteAnimation": "Emote Animation",
  "Label.Hat": "Hat",
  "Label.HairAccessory": "Hair Accessory",
  "Label.FaceAccessory": "Face Accessory",
  "Label.NeckAccessory": "Neck Accessory",
  "Label.ShoulderAccessory": "Shoulder Accessory",
  "Label.FrontAccessory": "Front Accessory",
  "Label.BackAccessory": "Back Accessory",
  "Label.WaistAccessory": "Waist Accessory",
  "Label.Skirt": "Skirt",
  "Label.Jacket": "Jacket",
  "Label.LeftShoe": "Left Shoe",
  "Label.RightShoe": "Right Shoe",
  "Label.Shirt": "Shirt",
  "Label.Sweater": "Sweater",
  "Label.MoodAnimation": "Mood Animation",
  "Label.DynamicHead": "Dynamic Head",
  "Label.SerialNumberDisplay": "#{serialNumber}",
  "Label.ItemOwnedCountSingular": "Owned Item ({itemCount})",
  "Label.Fee": "{feePercentage}% Fee:",
  "Action.ShowLess": "Show Less",
  "Label.TakeOffResaleConfirmation": "Are you sure you want to stop offering this item for resale?",
  "Label.SalePrice": "Sale Price:",
  "Heading.Marketplace": "Marketplace",
  "Label.Yes": "Yes",
  "Label.No": "No",
  "Label.Tradeable": "Tradeable",
  "Label.Tradable": "Tradable",
  "Action.SeeMore": "See More",
  "Label.HoldingPeriod": "Holding Period",
  "Heading.InExperienceOnly": "Available In Experience",
  "Label.InExperienceOnly": "The original sale of this item is only available in experience.",
  "Label.InExperiencePurchaseOnly":
    "The original sale of this item is only available in experience.",
  "Label.QuantityLeft": "Quantity Left: {remaining}/{total}",
  "Label.QuantityLimitReached":
    "The creator has limits on how many copies a single user can purchase from them.",
  "Label.PremiumForResell": "Roblox Plus is required for reselling",
  "Message.NoHoldingPolicy":
    "This item does not require a holding period, you can resell it as soon as you purchase it. Only premium users can resell items.",
  "Message.QuantityLimitReached":
    "Whoops! The creator has limits on how many copies a single user can purchase from them.",
  "Label.MaxPerUser": "Max Per User",
  "Heading.QuantityLimitReached": "Creator Limit Reached",
  "Label.Resellable": "Resellable",
  "Message.SoldOut": "This item is sold out.",
  "Message.CannotResell": "This item cannot be resold to others.",
  "Label.GetItFrom": "Get It From",
  "Message.ResellingDisabled":
    "This item cannot be sold to others. Reselling option has been disabled by the creator.",
  "Label.SoldIn": "Sold In",
  "Label.SoldOut": "Sold Out",
  "Message.HoldingPolicyL2":
    "After purchasing, original sales enter a hold for up to {purchaseDays} days. The item can only be resold after this holding period ends and resales will have a hold of up to {resaleDays} days. Only premium users can resell items.",
  "Message.HoldingPolicyL1":
    "Purchases from resale will have a hold of up to {days} days. The item can only be resold after this holding period ends. Only Plus users can resell items.",
  "Label.Attribution": "Made In",
  "Label.InSingleExperience": "In Experience",
  "Label.SaveAsCharacter": "Save as a Character",
  "Label.OriginalUnavailable": "Original is currently unavailable for purchase",
  "Label.TotalItems": "Total: {itemCount} items",
  "Label.Edit": "Edit",
  "Message.PurchaseLimit": "You can only purchase {purchaseLimit} items at a time",
  "Message.TwoStepVerficationPrompt":
    "You reached the daily purchase limit. Complete 2-Step Verification to continue purchase.",
  "Title.ReportSubmitted": "Report Submitted",
  "Heading.NeedMoreRobux": "Need More Robux?",
  "Message.WithRobux": "With Robux, you can upgrade your avatar, unlock special items, and more. ",
  "Message.RunningLowRobux": "Looks like you're running low",
  "Heading.TreatYourself": "Treat yourself",
  "Message.RedeemAGiftCard":
    "When you redeem a gift card, you'll get bonus code to unlock an exclusive virtual item.",
  "Action.ShopGiftCards": "Shop Gift Cards",
  "Message.GiftCardPurchase":
    "Buy a gift card for yourself and receive 2 exclusive virtual items for FREE",
  "Label.MinimumAmountCustom": "Minimum amount must be over {minimumAmount}.",
  "Action.Collapse": "Collapse",
  "Action.Expand": "Expand",
  "Label.Filter.TotalValue": "Total Value",
  "Action.ViewItems": "View Items",
  "Action.Reset": "Reset",
  "Action.LoadMore": "Load More",
  "Message.CharacterSaved": "Character saved",
  "Action.Done": "Done",
  "Action.AddItemsToCart": "Add {items} items to cart",
  "Message.SuccessfulPurchaseOfItems":
    "You have successfully purchased {numberOfItems} items for {totalPriceView}.",
  "Message.ItemsEquipped": "Items equipped",
  "Message.AvatarUpdateFailed": "Avatar update failed. Please try on the Avatar Editor.",
  "Message.CharacterCreationFailed": "Character creation failed. Please try on the Avatar Editor.",
  "Message.PurchaseComplete": "Purchase Complete",
  "Action.NotNow": "Not Now",
  "Message.SuccessfulAcquisitionOfItems": "You have successfully acquired {numberOfItems} items.",
  "Action.EquipItems": "Equip Items",
  "Title.IncludedItems": "Included Items",
  "Action.RemoveItemsFromCart": "Remove {items} items from Cart",
  "Title.ReportFailure": "Failed to submit report. Please try again later.",
  "Label.ItemsOwned": "Items Owned",
  "Message.ItemsInInventory": "These items are available in your inventory.",
  "Heading.ItemsRemovedFromCart": "Removed {itemCount} items from your cart",
  "Heading.ItemsAddedToCart": "Added {itemCount} items to your cart",
  "Label.DefaultBody": "Default Body",
  "Label.ClassicHead": "Classic Head",
  "Label.ClassicFace": "Classic Face",
  "Label.CreatorName": "Creator Name",
  "Label.SortByTypeAndAggregation": "Sort by {sortType}, {sortAggregation}",
  "Label.ByCreator": "By {creator}",
  "Label.SortByType": "Sort by {sortType}",
  "Action.Hid": "Hide",
  "Action.Show": "Show",
  "Label.ShowUnavailableItems": "Show Unavailable Items",
  "Action.DropdownSelected": "{optionName} selected",
  "Action.DropdownNotSelected": "{optionName} not selected",
  "Action.AddedToCart": "Added to cart",
  "Label.FullBody": "Full Body",
  "Label.Created": "Created",
  "Label.AllBodies": "All Bodies",
  "Label.NA": "N/A",
  "Label.AllBody": "All Body",
  "Action.CheckoutSingular": "Checkout 1 item",
  "Action.CheckoutPlural": "View Checkout ({count})",
  "Label.OutOfStock": "Out of Stock",
  "Label.Checkout.OutOfStock": "Out of Stock",
  "Label.Checkout.Unavailable": "Unavailable",
  "Label.Checkout.LimitReached": "Limit Reached",
  "Label.Checkout.OffSale": "Not For Sale",
  "Label.Checkout.InExperienceOnly": "Only in Experience",
  "Label.Checkout.SoldOut": "Sold Out",
  "Title.CheckoutSingular": "Checkout 1 item",
  "Title.CheckoutPlural": "Checkout {count} items",
  "Action.Checkout.UnavailableItems": "Got it",
  "Title.Checkout.UnavailableItems": "Unavailable Items",
  "Message.Checkout.UnavailableItems":
    "One or more items can’t be purchased. Please remove them before continuing.",
  "Label.PBR": "Materials",
  "Label.PBRInfo":
    "Avatar items with advanced materials use physically based rendering (PBR) to look more natural, with light and shadows that change and shine like they do in real life.",
  "Title.Checkout.TryOnMultipleItemsFtuxTitle": "Try on multiple items at once",
  "Title.Checkout.TryOnMultipleItemsFtuxBody":
    "As you tap, items will stack on your avatar so you can build a full look. You can only wear one per category.",
  "Action.Checkout.Wear": "Wear",
  "Title.Checkout.WearAvatarReplaceAllItemsTitle": "Wear Avatar?",
  "Label.Checkout.WearAvatarReplaceAllItemsBody":
    "Wearing this avatar will replace all the items you are currently wearing.",
  "Title.Checkout.ClearAllItemsOnAvatarTitle": "Clear all items?",
  "Label.Checkout.ClearAllItemsOnAvatarBody":
    "This will remove all the unowned items you are wearing on your avatar.",
  "Label.Checkout.DontWarnAgainText": "Don't warn me again",
  "Label.Checkout.CheckoutButtonFtuxTooltip": "See and remove items you're trying on here",
  "Label.PBRCombinedInfo":
    "Avatar items with Physically-Based Rendering (PBR) look more realistic, with light and shadows that change and shine like they do in real life.",
  "Checkout.WearAfterPurchase": "Wear after purchase",
  "Title.Checkout.PurchaseFailedSingular": "1 item could not be purchased",
  "Message.Checkout.PurchaseFailed": "To continue, review or remove the items",
  "Checkout.Title.PurchasedFailedPlural": "{count} items could not be purchased",
  "Title.Checkout": "Checkout",
  "Title.Checkout.PurchaseFailedPlural": "{count} items could not be purchased",
  "Action.Checkout.GoToCustomize": "Go to Customize",
  "Title.Checkout.GoToCustomizeTitle": "Go to Customize to Edit",
  "Label.Checkout.GoToCustomizeBody":
    "You can only wear or remove owned items in the Customize view.",
  "Action.Checkout.ManageInCustomize": "Manage in Customize",
  "Label.PBR.true": "Advanced",
  "Label.PBR.false": "Basic",
  "Feature.Catalog.Label.TotalItems": "Total: {itemCount} Items",
  "Feature.Catalog.Label.ClassicShirt": "Classic Shirt",
  "Feature.Catalog.Label.ClassicTShirt": "Classic T-Shirt",
  "Feature.Catalog.Label.TotalItemsParenthesis": "Total ({itemCount} items)",
  "Title.Checkout.ItemsPurchased": "{count} Items Purchased",
  "Title.Checkout.ItemRemovedSingular": "Item Removed",
  "Title.Checkout.ItemReplacedOnAvatarTitle": "Item Replaced",
  "Label.Checkout.ItemReplacedOnAvatarBody":
    "You can only wear one item per category. A new item will always replace the one you're currently wearing.",
  "Header.Checkout": "Checkout",
  "Label.Checkout.PriceChanged": "Price Changed",
  "Label.Clothing.BodySuits": "Bodysuits",
  "Label.TimedOptions": "Timed Options",
  "Label.Makeup": "Makeup",
  "Label.FaceMakeup": "Face",
  "Label.LipMakeup": "Lips",
  "Label.EyeMakeup": "Eyes",
  "Label.EyebrowMakeup": "Eyebrows",
  "Label.EyelashMakeup": "Eyelashes",
  "Label.SupportsHeadShapes": "Supports Head Shapes",
  "Label.TimedOptionDaysAbbreviation": "{days}d",
  "Label.Eyelashes": "Eyelashes",
  "Label.Eyebrows": "Eyebrows",
  "Label.TimedOptionDays": "{days} days",
  "Label.Permanent": "Permanent",
  "Label.TimedOptionsTooltipTitle": "Choose how long you keep it",
  "Label.TimedOptionsTooltipBody":
    "The timer starts after purchase, with options to extend or buy permanent",
  "Label.Options": "Options",
  "Message.TimedOptionsInYourInventoryUntil": "In your inventory until {date}",
  "Label.HeadShape": "Head Shape",
  "Label.Adjustable": "Adjustable",
  "Label.TimedOptionDaysTimerStarts": "{days} days (Timer starts when you buy)",
  "Message.PriceCouldBeDifferent": "Item type determines an item's pricing rules",
  "Action.UpdateInCart": "Update in cart",
  "Action.Replace": "Replace",
  "Title.Makeup.MakeupMax6LayersPromptTitle": "Replace bottom layer?",
  "Label.Makeup.MakeupMax6LayersPromptBody":
    "New makeup layers will always appear at the top, replacing the bottom layer until you free a slot.",
  "Label.Placement": "Placement",
  "Label.Top": "Top",
  "Label.Outerwear": "Outerwear",
  "Label.Bottom": "Bottom",
  "TrustedConnection.Label.Trusted": "Trusted",
  "Label.MakeupCartDescriptionText":
    "Any 6 eyes, lips and face, along with 1 eyelash and 1 eyebrow",
  "Label.Props": "Props",
  "Label.HandArmAccessory": "Hand & Arm Accessory",
  "Label.FullMask": "Full Mask",
  "Label.Subtotal": "Subtotal ({count} {itemWord})",
  "Label.Backgrounds": "Backgrounds",
  "Label.GetThisItemWithAnAgeCheck":
    "Get this item with an age check. {linkStart}Terms apply.{linkEnd}",
  "Message.AgeCheckCompleteInventory":
    "Age check complete. {itemName} will be in your inventory soon.",
  "Label.AgeCheckComplete": "Age check complete, get your free item",
  "Label.GetThisItemWithAnAgeCheckNoLink": "Get this item with an age check.",
  "Action.ViewTerms": "View terms",
  "Label.FreeItemWithAnAgeCheck": "Free item with an age check",
  "Action.Unlock": "Unlock",
  "Title.Checkout.OfferFailedToFetch": "Failed to fetch available offers, please try again later.",
  "Title.Checkout.OfferFailedToUpdate": "Failed to toggle offer, please try again later.",
  "Label.SaveOptions": "Save Options",
  "Label.RentOptionInfo":
    "Try this item out for 3 days at a lower price. Your timer starts after purchase.",
  "Label.RentOption": "Rent option",
  "Title.RentalFtuxText": "Rent to try an item out for 3 days",
  "Label.OfferApplied": "Offer Applied",
  "Text.OfferAppliedToHighestItem": "Offer applied to highest item",
  "Feature.Catalog.Label.AvatarBackgrounds": "Backgrounds",
  "Label.Attributes": "Attributes",
  "Label.AdvancedMaterials": "Advanced Materials",
  "Label.Emissive": "Emissive",
  "Label.ParticleEffects": "Particle Effects",
  "Label.EmissiveInfo":
    "Emissive item glows and gives off its own light, so it stays bright and visible even in dark environments.",
  "Label.ParticleEffectsInfo":
    "An item with particle effects gives off animated visuals, making it feel dynamic and alive.",
  "Action.Owned": "{count} owned",
  "Action.Try": "Try",
  "Message.SellingBelowAveragePrice":
    "This price is well below the recent average price of {averagePrice} Robux. Double-check the amount before you sell."
};
window.Roblox &&
  window.Roblox.BundleDetector &&
  window.Roblox.BundleDetector.bundleDetected("DynamicLocalizationResourceScript_Feature.Catalog");
