var Roblox = Roblox || {};
Roblox.LangDynamic = Roblox.LangDynamic || {};
Roblox.LangDynamic["Feature.Profile"] = {
  "Label.About": "About",
  "Label.Creations": "Creations",
  "Label.ShowLess": "Show Less",
  "Label.ReadMore": "Read More",
  "Label.SlideshowView": "Slideshow View",
  "Label.GridView": "Grid View",
  "Label.LoadMore": "Load More",
  "Label.PastUsername": "Past Usernames",
  "Label.WarningTitle": "Warning",
  "Label.Cancel": "Cancel",
  "Label.BlockWarningConfirm": "Block",
  "Label.UnblockWarningConfirm": "Unblock",
  "Label.BlockWarningBody": "Are you sure you want to block this user?",
  "Label.UnblockWarningBody": "Are you sure you want to unblock this user?",
  "Label.BlockWarningFooter":
    "When you've blocked a user, neither of you can directly contact the other.",
  "Label.JoinDate": "Join Date",
  "Label.PlaceVisits": "Place Visits",
  "Label.ForumPosts": "Forum Posts",
  "Action.SeeAll": "See All",
  "Action.Favorites": "Favorites",
  "Heading.ProfileGroups": "Communities",
  "Heading.PlayerAssetsBadges": "Badges",
  "Heading.PlayerAssetsClothing": "Clothing",
  "Heading.PlayerAssetsModels": "Models",
  "Heading.RobloxBadge": "Roblox Badges",
  "Heading.GameTitle": "Experiences",
  "Heading.Statistics": "Statistics",
  "Message.NoCreation": "{username} has no creations.",
  "Heading.Profile": "Profile",
  "Heading.Friends": "Friends",
  "Heading.FriendsNum": "Friends ({friendsCount})",
  "Heading.Collections": "Collections",
  "Heading.CurrentlyWearing": "Currently Wearing",
  "Heading.PlayerBadge": "Badges",
  "Heading.FavoriteGames": "Favorites",
  "Heading.Games": "Experiences",
  "Heading.Groups": "Communities",
  "Label.Members": "Members",
  "Label.Rank": "Rank",
  "Label.Friends": "Friends",
  "Label.Followers": "Followers",
  "Label.Following": "Following",
  "Label.ReportAbuse": "Report abuse",
  "Label.PastUsernames": "Previous usernames",
  "Label.Playing": "Active",
  "Label.Visits": "Visits",
  "Action.SlideshowView": "Slideshow View",
  "Action.GridView": "Grid View",
  "Action.SeeMore": "See More",
  "Action.SeeLess": "See Less",
  "Action.Inventory": "Inventory",
  "Action.Trade": "Trade",
  "Action.TradeItems": "Trade items",
  "Action.Unfriend": "Unfriend",
  "Action.Chat": "Chat",
  "Action.Message": "Message",
  "Action.Follow": "Follow",
  "Action.Unfollow": "Unfollow",
  "Action.BlockUser": "Block user",
  "Action.UnblockUser": "Unblock User",
  "Action.Accept": "Accept",
  "Action.AddFriend": "Add friend",
  "Action.Pending": "Pending",
  "Action.JoinGame": "Join",
  "Action.ImpersonateUser": "Impersonate user",
  "Action.UpdateStatus": "Update Status",
  "Action.Save": "Save",
  "Message.Sharing": "Sharing...",
  "Message.ChangeStatus": "What are you up to?",
  "Action.ConfirmBlockUser": "Block",
  "Description.BlockUserPrompt": "Are you sure you want to block this user?",
  "Description.BlockUserFooter":
    "When you've blocked a user, neither of you can directly contact the other.",
  "Action.ConfirmUnblockUser": "Unblock",
  "Description.UnblockUserPrompt": "Are you sure you want to unblock this user?",
  "Heading.BlockUserTitle": "Warning",
  "Action.CancelBlockUser": "Cancel",
  "Message.ErrorBlockLimit": "Operation failed! You may have blocked too many people.",
  "Message.ErrorGeneral": "Something went wrong. Please check back in a few minutes.",
  "Heading.AboutTab": "About",
  "Response.TooManyAttempts": "Too many attempts. Please try again later.",
  "Label.Quotation": '"{userStatus}"',
  "Label.Alias": "Alias",
  "Label.ChangeAlias": "Set Alias",
  "Description.ChangeAlias": "Only you can see this information",
  "Action.Close": "Close",
  "Message.AliasIsModerated": "Please avoid using full names or offensive language.",
  "Message.AliasHasError": "An error has occurred. Please try again later",
  "Description.AboutWarning": "Keep yourself safe, do not share personal details online.",
  "Description.PlaceholderStatus":
    "Tell the Roblox community about what you like to make, build, and explore...",
  "Description.Error": "Unable to update description, please try again later.",
  "Description.AboutSuccess": "Successfully updated description.",
  "Message.AcceptFriendRequestError": "Unable to accept friend request.",
  "Message.SendFriendRequestError": "Unable to send friend request.",
  "Message.RemoveFriendError": "Unable to unfriend user.",
  "Message.FollowError": "Unable to follow user.",
  "Message.UnfollowError": "Unable to unfollow user.",
  "Message.BlockError": "Unable to block user. You may have blocked too many people.",
  "Message.BlockRequestError": "Unable to block user.",
  "Message.ImpersonateUserError": "Unable to impersonate user.",
  "Message.UpdateStatusError": "Unable to update status.",
  "Label.QRCodeFriendRequest": "Sent from your QR code",
  "Label.CustomizeName": "Customize name",
  "Description.SetCustomName": 'Set a custom name for <font weight="medium">{displayName}</font>.',
  "Description.RecognizeFriendsByCustomName":
    "Recognize friends more easily by setting a custom name. Names imported from contacts and custom names are only visible to you.",
  "Message.InvalidAliasError": "Name cannot be saved. Try another name.",
  "Heading.PlayerAssetsModelsAndPackages": "Models & Packages",
  "Label.CustomizeNamePlaceholder": "Custom Name",
  "Description.SetCustomNameNoDisplayName": "Set a custom name.",
  "Heading.DisplayName": "Display Name",
  "Label.DisplayNameCaption":
    "This is the primary public name other users will see for you on Roblox.",
  "Label.CustomName": "Custom Name",
  "Tooltip.CustomNameProfile": "Recognize friends more easily by setting a custom name.",
  "Label.AgedUpDisplayNameCaption":
    "This is the primary public name other users will see for you on Roblox. Choose a name your friends will recognize you by, such as your real name.",
  "Heading.EditAgedUpDisplayName": "Edit Name",
  SetCustomName2: "Set a custom name for",
  "Description.SetCustomName2": "Set a custom name for",
  "Label.MoreSocialLinks": "+ {number} more",
  "Label.NicknameErrorMessageTooShort": "Name should have at least 2 characters.",
  "Label.NicknameErrorMessageTooLong": "Name should have at most 20 characters.",
  "Label.NicknameErrorMessageInvalidCharacters": "Name contains unsupported characters.",
  "Label.NicknameErrorMessageModerated": "Name is not appropriate for Roblox.",
  "Label.NicknameErrorMessageThrottled": "Your name has already been changed today.",
  "Label.NicknameErrorMessageInvalid": "Name is not valid.",
  "Action.SkipAddNickname": "Skip",
  "Action.AddNickname": "Add Name",
  "Heading.NicknameRequestSent": "Friend Request Sent",
  "Description.SetNicknamePrompt": "Add a name for {displayName} to recognize you.",
  "Description.NicknamePrivacy": "Only {displayName} will see this.",
  "Label.CustomNicknameDropdown": "Set Custom Name",
  "Label.TimeToChangeNickname": "You can change your name in {hours} hours.",
  "Description.SetNicknamePromptNoDisplayName": "Add a name for this user to recognize you.",
  "Description.NicknamePrivacyNoDisplayName": "Only this user will see this.",
  "Description.EnterNicknameTextbox": "Enter your nickname",
  "Description.SelectNicknameDropdown": "Select a name",
  "Header.Store": "Store",
  "Message.TooManyBlockedUsersError": "Block limit reached. Unblock someone to block more users.",
  "Message.ParentBlockedUserError":
    "Your parent blocked this user. Ask your parent to unblock this user in Settings.",
  "Message.UserAlreadyBlockedError": "This user is already blocked.",
  "Message.TargetNotBlockedError": "This user isn’t blocked—you're all set!",
  "Action.ShareProfile": "Share profile",
  "Description.RecognizeConnectionsByCustomName":
    "Recognize friends more easily by setting a custom name. Names imported from contacts and custom names are only visible to you.",
  "Label.AgedUpDisplayNameConnectionsCaption":
    "This is the primary public name other users will see for you on Roblox. Choose a name people will recognize you by, such as your real name.",
  "Message.TargetBlockedOnPlatform": "This user is blocked on another platform.",
  "Label.Connections": "Friends",
  "Label.Connection": "Friend",
  "Label.RemoveConnection": "Remove Friend",
  "Label.AddConnection": "Add friend",
  "Action.More": "{underlineStart}more{underlineEnd}.",
  "Label.NoSocialLink": "No social links yet",
  "Label.NoPreviousName": "No previous names",
  "Label.Others": "Others",
  "Label.NoBioYet": "No bio yet",
  "Label.AboutDetailsHeading": "About {name}",
  "Label.JoinedIn": "Joined in {year}",
  "Action.EditAvatar": "Edit avatar",
  "Label.Follower": "Follower",
  "Label.PreviousNames": "Previous names",
  "Label.EditBio": "Edit bio",
  "Label.More": "more",
  "Heading.SocialLinks": "Social links",
  "Action.Add": "Add",
  "Action.Copy": "Copy",
  "Action.EditProfile": "Edit profile",
  "Action.Unblock": "Unblock",
  "Action.Block": "Block",
  "Action.Report": "Report",
  "Message.CopySuccess": "Link copied to clipboard",
  "Message.CopyFailure": "Failed to copy link to clipboard",
  "Message.FailedToJoin": "Failed to join user",
  "Message.UserDoesNotExist": "User does not exist",
  "Message.GracefulDegradation":
    "Whoa, it's busy in here! We're showing a simplified profile to keep things running smoothly. Please check back later to see the full view.",
  "Label.ContextualMenu": "Contextual menu",
  "Action.OpenContextualMenu": "Open contextual menu",
  "Error.FailedToStartChat": "Failed to start chat. Please try again.",
  "Error.FailedToJoinExperience": "Failed to join experience. Please try again.",
  "Action.SignUpToAddConnection": "Sign up to add",
  "Action.LogInToAddConnection": "Log in to add",
  "Message.SendConnectionRequestError": "Unable to send friend request.",
  "Heading.ProfileCompletion": "Complete your profile",
  "Title.AgeCheck": "Get an age check",
  "Description.AgeCheck": "This allows you to chat safely. It only takes a moment.",
  "Action.ExploreMarketplace": "Explore marketplace",
  "Description.AddConnections": "Connect with others to play, chat, and explore together.",
  "Description.CustomizeAvatar": "Browse unique items and express yourself.",
  "Title.AddConnections": "Add friends",
  "Title.CustomizeAvatar": "Complete your look",
  "Action.UnlockChat": "Unlock chat",
  "Action.FindPeople": "Find people",
  "Action.HideForNow": "Hide for now",
  "Label.RemoveFriend": "Unfriend",
  "Label.AddFriend": "Add friend",
  "Label.AgedUpDisplayNameFriendsCaption":
    "This is the primary public name other users will see for you on Roblox. Choose a name your friends will recognize you by, such as your real name.",
  "Label.Friend": "Friend",
  "Title.AddFriends": "Add friends",
  "Action.ViewProfile": "View profile",
  "Label.PlayingExperience": "playing <b>{experienceName}</b>",
  "Message.RemoveTrustedFriendError": "Unable to remove trusted friend",
  "Label.NoFriendsYet": "{username} doesn’t have any friends yet.",
  ReportAbuse: "Report abuse",
  "Action.ReportAbuse": "Report abuse",
  "Label.UserIsPlayingExperience": "<b>{userName}</b> is playing <b>{experienceName}</b>",
  "Action.SendRobux": "Send Robux",
  "Title.CheckOutFrames": "Check out frames",
  "Description.ProfileFrameUpsell": "Spice up your profile picture with a frame.",
  "Action.TryItOut": "Try it out",
  "Heading.ProfileFrame": "Profile frame",
  "Heading.ProfilePictureSaved": "Profile picture saved successfully"
};
window.Roblox &&
  window.Roblox.BundleDetector &&
  window.Roblox.BundleDetector.bundleDetected("DynamicLocalizationResourceScript_Feature.Profile");
