var Roblox = Roblox || {};
Roblox.LangDynamic = Roblox.LangDynamic || {};
Roblox.LangDynamic["Feature.Groups"] = {
  "Action.MakePrimaryGroup": "Make Primary Community",
  "Label.CreateGroupTooltip": "Create a new community",
  "Label.CreateGroupBuildersClubTooltip":
    "Creating a community requires a Roblox Premium membership.",
  "Label.ManageGroupCreations": "Create or manage community items.",
  "Label.NoGames": "No experiences are associated with this community.",
  "Label.NoStoreItems": "No items are for sale in this community.",
  "Label.NoAllies": "This community does not have any allies.",
  "Label.NoEnemies": "This community does not have any enemies.",
  "Label.NoMembersInRole": "No community members are in this role.",
  "Label.NoWallPosts": "Nobody has said anything yet...",
  "Label.WallPostPlaceholder": "Say something...",
  "Label.MaxGroupsTooltip": "You may only be in a maximum of {maxGroups} communities at one time",
  "Label.GroupClosed": "Community Closed",
  "Label.GroupLocked": "This community has been locked",
  "Label.OnlyBcCanJoin": "Only Builders Club members can join",
  "Label.NoOne": "No One!",
  "Label.Warning": "Warning",
  "Label.Loading": "Loading...",
  "Label.Success": "Success",
  "Action.GroupAdmin": "Community Admin",
  "Action.ClaimOwnership": "Claim Ownership",
  "Action.RemovePrimary": "Remove Primary",
  "Action.MakePrimary": "Make Primary",
  "Action.LeaveGroup": "Leave Community",
  "Action.AdvertiseGroup": "Advertise Community",
  "Action.AuditLog": "Audit Log",
  "Action.CreateGroup": "Create Community",
  "Action.Upgrade": "Upgrade",
  "Action.UpgradeToJoin": "Upgrade to Join",
  "Action.JoinGroup": "Join Community",
  "Action.CancelRequest": "Cancel request",
  "Action.Post": "Post",
  "Action.ExileUser": "Exile User",
  "Action.Delete": "Delete",
  "Action.Close": "Close",
  "Action.Exile": "Exile",
  "Action.Cancel": "Cancel",
  "Action.ReportAbuse": "Report abuse",
  "Message.DefaultError": "An error occurred.",
  "Message.LeaveGroupError": "Unable to leave community.",
  "Message.MakePrimaryError": "Unable to make primary community.",
  "Message.RemovePrimaryError": "Unable to remove primary community.",
  "Message.JoinGroupError": "Unable to join community.",
  "Message.ClaimOwnershipError": "Unable to claim ownership of community.",
  "Message.LoadGroupError": "Unable to load community.",
  "Message.LoadGroupMembershipsError": "Unable to load user membership information.",
  "Message.LoadUserGroupMembershipError": "Unable to load community member information.",
  "Message.SendGroupShoutError": "Unable to send community shout.",
  "Message.LoadGroupMetadataError": "Unable to load community info.",
  "Message.ExileUserError": "Unable to exile user.",
  "Message.DeleteWallPostsByUserError": "Unable to delete wall posts by user.",
  "Message.BuildGroupRolesListError": "Unable to load members for selected role.",
  "Message.SendPostError": "Unable to send post.",
  "Message.LoadWallPostsError": "Unable to load wall posts.",
  "Message.GetGroupRelationshipsError": "Unable to load community affiliates.",
  "Message.DeleteWallPostError": "Unable to delete wall post.",
  "Message.ClaimOwnershipSuccess": "Successfully claimed ownership of community.",
  "Message.DeleteWallPostSuccess": "Successfully deleted wall post.",
  "Message.JoinGroupSuccess": "Successfully joined the community.",
  "Message.JoinGroupPendingSuccess": "Requested to join community, your request is pending.",
  "Description.MakePrimaryGroupWarning":
    "Are you sure you want to make this your primary community?",
  "Description.RemovePrimaryGroupWarning":
    "Are you sure you want to remove your primary community?",
  "Description.LeaveGroupWarning": "Are you sure you want to leave this community?",
  "Description.LeaveGroupAsOwnerWarning": "This will leave the community ownerless.",
  "Description.ObcMaxGroups": "You have joined the maximum number of communities.",
  "Description.NoneMaxGroups": "Upgrade to Roblox Premium to join more communities.",
  "Description.OtherBcMaxGroups": "Upgrade your Builders Club to join more communities.",
  "Description.WallPrivacySettings":
    "Your privacy settings do not allow you to post to community walls. Click here to adjust these settings.",
  "Description.ClothingRevenue":
    "Communities have the ability to create and sell official shirts, pants, and t-shirts! All revenue goes to community funds.",
  "Description.ExileUserWarning": "Are you sure you want to exile this user?",
  "Description.DeleteAllPostsByUser": "Also delete all posts by this user.",
  "Heading.Funds": "Funds",
  "Heading.About": "About",
  "Heading.Wall": "Wall",
  "Heading.Store": "Store",
  "Heading.Games": "Experiences",
  "Heading.Allies": "Allies",
  "Heading.Enemies": "Enemies",
  "Heading.Members": "Members",
  "Heading.Rank": "Rank",
  "Heading.Affiliates": "Affiliates",
  "Heading.Description": "Description",
  "Heading.GroupShout": "Community Shout",
  "Heading.Shout": "Shout",
  "Label.ShoutPlaceholder": "Enter your shout",
  "Heading.Primary": "Primary",
  "Action.GroupShout": "Community Shout",
  "Label.Funds": "Funds",
  "Heading.ExileUserWarning": "Warning",
  "Label.DeleteAllPostsByUser": "Also delete all posts by this user.",
  "Heading.LeaveGroup": "Leave Community",
  "Label.WallPostsUnavailable": "Wall posts are temporarily unavailable, please check back later.",
  "Action.Yes": "Yes",
  "Heading.RemovePrimaryGroup": "Remove Primary Community",
  "Heading.MakePrimaryGroup": "Make Primary Community",
  "Label.ByOwner": "By",
  "Label.Members": "{memberCount, plural, =0 {# Members} =1 {# Member} other {# Members}}",
  "Label.CreateGroupPremiumTooltip": "Creating a community requires a Roblox Premium membership.",
  "Label.OnlyPremiumCanJoin": "Only users with membership can join",
  "Description.NoneMaxGroupsPremium": "Upgrade to Roblox Premium to join more communities.",
  "Description.PremiumMaxGroups": "You have joined the maximum number of communities.",
  "Action.ConfigureGroup": "Configure Community",
  "Heading.Payouts": "Payouts",
  "Message.UnknownError": "Unknown error",
  "Message.InvalidGroup": "Community is invalid or does not exist.",
  "Message.TooManyIds": "Too many ids in request.",
  "Message.InvalidIdsError": "Ids could not be parsed from request.",
  "Message.InvalidIds": "Ids could not be parsed from request.",
  "Message.InvalidRelationshipType": "Community relationship type is invalid.",
  "Message.InsufficientPermissionsForRelationships":
    "You don't have permission to manage this community's relationships.",
  "Message.UnauthorizedForPostStatus": "You are not authorized to post a shout for this community.",
  "Message.MissingGroupStatusContent": "Missing community shout content.",
  "Message.InvalidPaginationParameters": "Invalid or missing pagination parameters.",
  "Message.UnauthorizedForViewGroupPayouts":
    "You don't have permission to view this community's payouts.",
  "Message.InvalidMembership": "User must have Roblox Premium membership.",
  "Message.MaxGroups": "User is in maximum number of communities.",
  "Message.InvalidName": "The name is invalid.",
  "Message.NameModerated": "The name is moderated.",
  "Message.InvalidGroupIcon": "The community icon is invalid.",
  "Message.MissingGroupIcon": "The community icon is missing from the request.",
  "Message.TooManyRequests": "Too many requests.",
  "Message.DescriptionTooLong": "The description is too long.",
  "Message.NameTooLong": "The name is too long.",
  "Message.NameTaken": "The name has been taken.",
  "Message.GroupCreationDisabled": "Community creation is currently disabled.",
  "Message.InvalidGroupId": "The community is invalid or does not exist.",
  "Message.InvalidRoleSetId": "The roleset is invalid or does not exist.",
  "Message.InvalidUser": "The user is invalid or does not exist.",
  "Message.UnauthorizedToManageMember": "You do not have permission to manage this member.",
  "Message.PassCaptchaToJoin": "You must pass the captcha test before joining this community.",
  "Message.InsufficientGroupSpace": "You are already in the maximum number of communities.",
  "Message.AlreadyRequested": "You have already requested to join this community.",
  "Message.AlreadyMember": "You are already a member of this community.",
  "Message.InsufficientMembership":
    "You do not have the Roblox Premium membership necessary to join this community.",
  "Message.TooManyAttempts": "Too many attempts to join the community. Please try again later.",
  "Message.UnauthorizedToClaimGroup": "You are not authorized to claim this community.",
  "Message.CannotClaimGroupWithOwner": "This community already has an owner.",
  "Message.TooManyAttemptsToClaimGroups":
    "Too many attempts to claim communities. Please try again later.",
  "Message.GroupClosed": "You cannot join a closed community.",
  "Message.UnauthorizedToViewRolesetPermissions":
    "You are not authorized to view permissions for this roleset.",
  "Message.UserNotInGroup": "You aren't a member of the community specified.",
  "Message.NoPrimary": "The user specified does not have a primary community.",
  "Message.UnauthorizedToViewWall": "You do not have permission to access this community wall.",
  "Message.InvalidGroupWallPostId": "The community wall post id is invalid or does not exist.",
  "Message.TooManyPosts": "You are posting too fast, please try again in a few minutes.",
  "Message.InvalidWallPostContent":
    "Your post was empty, white space, or more than 500 characters.",
  "Message.PassCaptchaToPost": "Captcha must be solved to post to the community wall.",
  "Message.FeatureDisabled": "The feature is disabled.",
  "Message.InsufficientPermission": "Insufficient permissions to complete the request.",
  "Message.InvalidPayoutType": "Invalid payout type.",
  "Message.InvalidAmount": "The amount is invalid.",
  "Message.InvalidRecipient": "The recipient is invalid.",
  "Description.ReportAbuseDescription": "What would you like to report?",
  "Action.Report": "Report",
  "Heading.Role": "Role",
  "Heading.NameOrDescription": "Name, Icon, or Description",
  "Message.LoadGroupGamesError": "Unable to load experiences.",
  "Message.LoadGroupStoreItemsError": "Unable to load store items.",
  "Message.GroupMembershipsUnavailableError":
    "The community membership system is temporarily unavailable. Please try again later.",
  "Label.NoResults": 'No results for "{searchTerm}"',
  "Label.SearchGroups": "Search Communities",
  "Label.PublicGroup": "Public",
  "Label.PrivateGroup": "Private",
  "Message.SearchTermEmptyError": "Search term is empty",
  "Message.SearchTermFilteredError": "Search term was filtered",
  "Message.SearchTermCharactersLimit": "The search term needs to be between 2 and 50 characters",
  "Label.CreateGroup": "Create Community",
  "Label.CreateGroupDescription": "Description (optional)",
  "Label.CreateGroupName": "Name your community",
  "Label.CreateGroupEmblem": "Emblem",
  "Action.Purchase": "Purchase",
  "Label.CreateGroupFee": "Community Creation Fee",
  "Heading.Settings": "Settings",
  "Label.AnyoneCanJoin": "Anyone Can Join",
  "Label.ManualApproval": "Manual Approval",
  "Heading.GroupPurchase": "Community Purchase Confirmation",
  "Description.PurchaseBody": "Would you like to create this community for",
  "Message.TooManyGroups":
    "You have reached the community capacity. Please leave a community before creating a new one.",
  "Message.InsufficientRobux": "You do not have enough Robux to create the community.",
  "Message.NameInvalid": "Name is missing or has invalid characters.",
  "Message.GroupIconInvalid": "Icon is missing or invalid.",
  "Message.GroupIconTooLarge": "Icon cannot be larger than {maxSize} mb.",
  "Message.DuplicateName": "Name is already taken. Please try another.",
  "Label.GroupSearchResults": "Community Results For {searchTerm}",
  "Message.RemoveMember": "{actor} kicked user {user}",
  "Message.DeletePost": "{actor} deleted post by user {user}",
  "Message.AcceptJoinRequest": "{actor} accepted user {user}'s join request",
  "Message.DeclineJoinRequest": "{actor} declined user {user}'s join request",
  "Message.PostStatus": '{actor} changed the community shout to "{groupStatus}"',
  "Message.ChangeRank": "{actor} changed user {user}'s rank from {oldRoleSet} to {newRoleSet}",
  "Message.BuyAd": "{actor} bid {bid} on group ad {adName}",
  "Message.SendAllyRequest": "{actor} sent an ally request to community {group}",
  "Message.CreateEnemy": "{actor} declared community {group} as an enemy",
  "Message.AcceptAllyRequest": "{actor} accepted community {group}'s ally request",
  "Message.DeclineAllyRequest": "{actor} declined community {group}'s ally request",
  "Message.DeleteAlly": "{actor} removed community {group} as an ally",
  "Message.DeleteEnemy": "{actor} removed community {group} as an enemy",
  "Message.AddGroupPlace": "{actor} added experience {game} as a community experience",
  "Message.DeleteGroupPlace": "{actor} removed experience {game} as a community experience",
  "Message.CreateItems": "{actor} created the community item {item}",
  "Message.ConfigureItems": "{actor} configured the community item {item}",
  "Message.ChangeOwner": "{actor} changed the community owner. {user} is the new community owner",
  "Message.ChangeOwnerEmpty": "There is no owner of the community",
  "Message.Rename": "{actor} renamed current community to {newName}",
  "Message.Delete": "{actor} deleted current community",
  "Message.AdjustCurrencyAmountsIncreased": "{actor} increased group funds by {amount}",
  "Message.AdjustCurrencyAmountsDecreased": "{actor} decreased group funds by {amount}",
  "Message.Abandon": "{actor} (group owner) abandoned the community",
  "Message.Claim": "{actor} claimed ownership of the community",
  "Message.ChangeDescription": '{actor} changed the description to "{newDescription}"',
  "Message.SpendGroupFunds": "{actor} spent {amount} of group funds for: {item}",
  "Message.InviteToClan": "{actor} invited user {user} to the clan",
  "Message.KickFromClan": "{actor} kicked user {user} out of the clan",
  "Message.CancelClanInvite": "{actor} cancelled {user}'s clan invite",
  "Message.BuyClan": "{actor} bought a group clan",
  "Message.CreateAsset": "{actor} created asset {item}",
  "Message.UpdateAsset": "{actor} created new version {version} of asset {item}",
  "Message.UpdateAssetRevert":
    "{actor} reverted asset {item} from version {version} to {oldVersion}",
  "Message.ConfigureAsset": "{actor} updated asset {item}: {actions}",
  "Message.CreateDeveloperProduct": "{actor} created developer product with id {id}",
  "Message.ConfigureGame": "{actor} updated {game}: {actions}",
  "Message.ConfigureGameDeveloperProduct": "{actor} updated developer product {id}: {actions}",
  "Message.Lock": "{actor} locked the community",
  "Message.Unlock": "{actor} unlocked the community",
  "Message.CreateGamePass": "{actor} created a Pass for {game}: {gamePass}",
  "Message.CreateBadge": "{actor} created the badge {badge}",
  "Message.ConfigureBadgeEnabled": "{actor} enabled the badge {badge}",
  "Message.ConfigureBadgeDisabled": "{actor} disabled the badge {badge}",
  "Message.ConfigureBadgeUpdate": "{actor} configured the badge {badge}",
  "Heading.Date": "Date",
  "Heading.User": "User",
  "Label.All": "All",
  "Label.DeletePost": "Delete post",
  "Label.RemoveMember": "Remove Member",
  "Label.AcceptJoinRequest": "Accept Join Request",
  "Label.DeclineJoinRequest": "Decline Join Request",
  "Label.PostStatus": "Post Shout",
  "Label.ChangeRank": "Change Rank",
  "Label.BuyAd": "Buy Ad",
  "Label.SendAllyRequest": "Send Ally Request",
  "Label.CreateEnemy": "Create Enemy",
  "Label.AcceptAllyRequest": "Accept Ally Request",
  "Label.DeclineAllyRequest": "Decline Ally Request",
  "Label.DeleteAlly": "Delete Ally",
  "Label.DeleteEnemy": "Delete Enemy",
  "Label.AddGroupPlace": "Add Community Place",
  "Label.RemoveGroupPlace": "Remove Community Place",
  "Label.CreateItems": "Create Avatar Items",
  "Label.ConfigureItems": "Configure Items",
  "Label.SpendGroupFunds": "Spend Community Funds",
  "Label.ChangeOwner": "Change Owner",
  "Label.Delete": "Delete",
  "Label.AdjustCurrencyAmounts": "Adjust Currency Amounts",
  "Label.Abandon": "Abandon",
  "Label.Claim": "Claim",
  "Label.Rename": "Rename",
  "Label.ChangeDescription": "Change Description",
  "Label.InviteToClan": "Invite to Clan",
  "Label.KickFromClan": "Kick from Clan",
  "Label.CancelClanInvite": "Cancel Clan Invite",
  "Label.BuyClan": "Buy Clan",
  "Label.CreateGroupAsset": "Create Community Asset",
  "Label.UpdateGroupAsset": "Update Community Asset",
  "Label.ConfigureGroupAsset": "Configure Community Asset",
  "Label.RevertGroupAsset": "Revert Community Asset",
  "Label.CreateGroupDeveloperProduct": "Create Community Developer Product",
  "Label.ConfigureGroupDevelopmentItem": "Configure Community Development Item",
  "Label.ConfigureGroupGame": "Configure Community \nExperience",
  "Label.Lock": "Lock",
  "Label.Unlock": "Unlock",
  "Label.CreateGamePass": "Create Pass",
  "Label.ModerateDiscussion": "Moderate Discussion",
  "Label.CreateBadge": "Create Badge",
  "Label.ConfigureBadge": "Configure Badge",
  "Label.SavePlace": "Save Place",
  "Label.PublishPlace": "Publish Place",
  "Label.SearchUsers": "Search Users",
  "Message.LoadGroupListError": "Unable to load community list.",
  "Label.DeleteGroupPlace": "Delete Community Place",
  "Heading.ConfigureGroup": "Configure {groupName}",
  "Message.UnkownError": "An unknown error occurred.",
  "Message.SearchTermFiltered": "Search term not appropriate for Roblox.",
  "Message.SearchTermEmpty": "Search term was left empty.",
  "Message.SearchTermConstraint": "Search terms can be 2 to 50 characters long.",
  "Heading.Purchaser": "Purchaser",
  "Heading.Amount": "Amount",
  "Heading.Transactions": "Transactions",
  "Message.NoTransactions": "No transactions have been completed.",
  "Message.Transaction": "Sold {item}",
  "Message.TransactionForPlace": "Sold {item} for {place}",
  "Message.InvalidTargetGroup": "Target community is invalid or does not exist",
  "Message.CannotHaveRelationshipWithSelf":
    "Your community cannot establish a relationship with itself.",
  "Message.GroupCannotDeclareEnemies": "Your community does not allow enemy declarations.",
  "Message.CannotHaveRelationshipWithGroup": "Other community does not allow enemy declarations.",
  "Message.DuplicateRelationship":
    "Your community already has a relationship with the target community.",
  "Message.GroupBlocked": "You are blocked from communicating with this user.",
  "Message.RelationshipRequestDoesNotExist": "Relationship request does not exist.",
  "Message.RelationshipDoesNotExist": "Relationship does not exist.",
  "Message.TargetUserNotInGroup": "User is not a member of the community.",
  "Message.UserHasInsufficientMembership":
    "The user does not have the necessary level of premium membership.",
  "Message.UnauthorizedToChangeOwner":
    "You are not authorized to change the owner of this community.",
  "Message.InvalidGroupJoinRequest": "The community join request is invalid.",
  "Label.SearchMembers": "Search Members",
  "Message.NoPendingRequests": "There are no pending member requests.",
  "Message.UnableToAcceptAllRequests": "Unable to accept all requests. Please try again.",
  "Message.UnableToDeclineAllRequests": "Unable to decline all requests. Please try again.",
  "Message.UnableToRemoveAffiliate": "Unable to remove community affiliate.",
  "Message.UnableToUpdateRole": "Unable to update the user's role.",
  "Message.SuccessfullyUpdatedRole": "Successfully updated user's role",
  "Heading.Categories": "Categories",
  "Label.SaleOfGoods": "Sale of Goods",
  "Label.PendingSales": "Pending Sales",
  "Label.GroupPayouts": "Community Revenue Payouts",
  "Message.UnableToLoadRevenue": "Unable to load revenue summary",
  "Action.DeleteRole": "Delete role",
  "Message.DeleteRoleset": "Are you sure you want to delete {role}?",
  "Message.RoleDeleteSuccess": "Role successfully deleted.",
  "Message.RoleDeleteFail": "Unable to delete role.",
  "Message.RoleUpdateSuccess": "Role successfully updated.",
  "Message.RoleUpdateFail": "Unable to update role.",
  "Message.PermissionUpdateSuccess": "Permission successfully updated.",
  "Message.PermissionUpdateFail": "Unable to update permission.",
  "Label.ViewWall": "View community wall",
  "Label.ViewStatus": "View community shout",
  "Label.PostToWall": "Post on community wall",
  "Label.PostToStatus": "Post community shout",
  "Label.DeleteFromWall": "Delete community wall posts",
  "Label.InviteMembers": "Accept join requests",
  "Label.RemoveMembers": "Kick lower-ranked members",
  "Label.ChangeRanks": "Manage lower-ranked member ranks",
  "Label.ManageRelationships": "Manage allies and enemies",
  "Label.CreateItem": "Create Avatar Items",
  "Label.ManageItems": "Configure avatar items",
  "Label.AdvertiseGroup": "Advertise the community",
  "Label.SpendGroupFund": "Spend community funds",
  "Label.ManageGroupGames": "Create and edit community experiences",
  "Label.ViewAuditLogs": "View audit log",
  "Heading.PostsPermissions": "Posts",
  "Heading.MembershipPermissions": "Members",
  "Heading.EconomyPermissions": "Assets",
  "Heading.ManagementPermissions": "Miscellaneous",
  "Message.RankReserved":
    "Ranks must be between {minRankPlusOne} and {maxRankMinusOne}. {minRank} and {maxRank} are reserved for guests and the owner.",
  "Action.CreateRole": "Create role",
  "Message.PurchaseRole": "Purchasing a new role will cost {cost}",
  "Message.TransactionBalance": "Your balance after this transaction will be",
  "Label.UseGroupFunds": "Use community funds to purchase this role",
  "Message.NameFieldEmpty": "The name field cannot be empty",
  "Message.NotEnoughFunds": "You do not have enough funds to purchase this role",
  "Label.PermDeleteRole": "Permanently delete this role",
  "Message.RoleWithUsers":
    "There {amount, plural, =0 {are # users} =1 {is # user} other {are # users}} in this role. You cannot delete a role with users",
  "Message.UnableToPurchaseRole": "Failed to process payment to purchase role.",
  "Message.RoleLimitReached": "Limit for roles have been reached on this community.",
  "Message.UsersInRole": "There are users in this role.",
  "Message.CannotRemoveRole": "Cannot remove any more roles.",
  "Message.CannotDeleteRole": "Cannot delete this role.",
  "Message.MissingRoleName": "Missing role name.",
  "Message.MissingRoleRank": "Missing role rank.",
  "Message.RoleNameExists": "Role name already exists.",
  "Message.RankOutOfBounds": "Rank value is out of bounds.",
  "Message.RoleNameTooLong": "The role name is too long.",
  "Message.RoleDescriptionTooLong": "The roles description is too long.",
  "Message.UnauthorizedToEditPermissions":
    "You are not authorized to view/edit permissions for this role.",
  "Message.ImmutableRole": "This role's permissions can not be modified.",
  "Heading.GroupSearchCategoryBuilding": "Building",
  "Heading.GroupSearchCategoryMilitary": "Military",
  "Heading.GroupSearchCategoryRoleplaying": "Roleplaying",
  "Heading.GroupSearchCategoryFan": "Fan",
  "Label.Percentage": "Percentage",
  "Label.RevenueToGroupFund": "Revenue going to community fund:",
  "Label.PayingOut": "Paying out:",
  "Label.RemainingFunds": "Remaining Funds:",
  "Heading.RecurringPayout": "Recurring Payout",
  "Heading.OneTimePayout": "One-time Payout",
  "Label.AddMember": "Add Member",
  "Label.DistributeBy": "Distributing Robux by:",
  "Label.AvailableFunds": "Available Funds",
  "Message.NoFundsDistribute": "You do not have any funds to distribute.",
  "Message.CannotDeleteThisRole": "Cannot delete this role.",
  "Message.CannotUpdateGuest": "Cannot update Guest role.",
  "Message.CannotUpdateOwner": "Cannot update Owner role rank.",
  "Message.TooManyRecipients": "Too many recipients.",
  "Message.PaidOutRecently": "Community has paid out too recently. Please wait and try again.",
  "Message.DescriptionEmpty": "Your community description was empty.",
  "Message.InvalidFileType": "Invalid file type for community icon.",
  "Label.Ownership": "Ownership",
  "Label.ChangeGroupOwner": "Change the community's owner",
  "Label.Username": "Username",
  "Label.SelectNewOwner": "Select the new community owner",
  "Label.GroupFunds": "Community Funds:",
  "Action.GoToDetails": "Go to Details",
  "Message.UserIsOwner": "User is already the owner.",
  "Message.MaxRoles": "A maximum of 40 roles are allowed.",
  "Message.TransactionsBalance": "Your balance after this transaction will be {balance}",
  "Heading.Requests": "Requests",
  "Label.AllowDeclarations": "Allow enemy declarations",
  "Label.FundsVisible": "Community funds publicly visible",
  "Label.GamesVisible": "Community experiences are visible on the community home page",
  "Label.MustBeAccepted": "User requests must be accepted to join community",
  "Label.NoLongerModify": "If you turn this setting off, you will no longer be able to modify it",
  "Label.PremiumOnly": "Premium Only",
  "Message.SettingUpdated": "Setting successfully updated",
  "Message.SettingFail": "Unable to update setting",
  "Heading.Information": "Information",
  "Heading.SocialLinks": "Social Links",
  "Heading.Revenue": "Revenue",
  "Heading.Summary": "Summary",
  "Heading.RecurringPayouts": "Recurring Payouts",
  "Heading.Roles": "Roles",
  "Heading.AuditLog": "Audit Log",
  "Action.BackToGroup": "Back to Community",
  "Message.YouAreOwner": "You are already the owner of this community.",
  "Message.CannotChangeOwnRole": "You cannot change your own role.",
  "Message.NotEnoughFundsDistribute": "You do not have enough funds to distribute this amount.",
  "Message.MemberAdded": "Member was already added to payout.",
  "Message.ValueMustBeWhole": "Value must be a whole number.",
  "Heading.JoinRequirements": "Join Requirements",
  "Heading.GroupProfile": "Community Profile",
  "Message.MemberNotFound": "Member does not exist within this role.",
  "Label.AddPayoutRecipient": "Add Payout Recipient",
  "Label.EnterPayoutRecipient": "Enter the payout recipient's username",
  "Message.NoAllyRequests": "No ally requests",
  "Message.UnableToLoadAllyRequests": "Unable to load ally requests",
  "Label.DeclareEnemy": "Declare Enemy",
  "Description.EnterGroupName": "Enter the community name",
  "Label.GroupName": "Community Name",
  "Action.Send": "Send",
  "Action.Request": "Request",
  "Label.Total": "Total",
  "Description.PendingTransaction": "Pending",
  "Description.PendingSales":
    "Pending sales are not included in your total until released, which could take up to a few days",
  "Message.SettingsLoadFail": "Unable to load community settings.",
  "Message.ConfigMetadataLoadFail": "Could not load community configuration metadata.",
  "Message.PercentagePaidOut": "{percentage}% of the group's proceeds will be paid out",
  "Message.AmountPaidOut": "{amount} Robux were paid out to users from the group",
  "Heading.RemoveAlly": "Remove Ally",
  "Heading.RemoveEnemy": "Remove Enemy",
  "Description.RemoveAlly": "Are you sure you want to remove this community as an ally?",
  "Description.RemoveEnemy": "Are you sure you want to remove this community as an enemy?",
  "Action.AcceptAll": "Accept all",
  "Action.DeclineAll": "Decline All",
  "Label.EnemyDeclarationsNotEnabled":
    "Enemy declarations are not enabled. Please update your settings if you would like to enable this feature.",
  "Message.NoRecordsFound": "No records found.",
  "Description.ChangeOwnerWarning":
    "This is a permanent change and you will lose all of the privileges of community ownership. This includes the ability to keep community items on sale if the new owner does not have Roblox Premium.",
  "Message.LoadTransactionsError": "Unable to load transactions.",
  "Heading.Sales": "Sales",
  "Message.LoadAuditLogsError": "Unable to load audit logs.",
  "Heading.Item": "Item",
  "Message.ForPlace": "For {place}",
  "Message.PurchasedBy": "Purchased by {user}",
  "Label.GroupPremiumPayouts": "Community Premium Payouts",
  "Label.PendingRobux": "Pending Robux",
  "Description.PendingRobux":
    "Pending Robux are not included in your total until released, which could take up to a few days",
  "Description.PurchaseBodyAmount": "Would you like to create this community for {amount}?",
  "Description.CreateGroup":
    "Create your own community! Invite all of your friends, and duke it out with all your rivals!",
  "Description.JoinGroup":
    "Join a community to connect with people like you! Communities exist for all types of communities - fan clubs, help communities, hobbies, corporations, and more. Communities have their own walls and shared places.",
  "Heading.JoinGroup": "Join a Community",
  "Action.SeeAll": "See All",
  "Message.UserAlreadyAdded": "User is already a payout recipient.",
  "Message.SearchTermMinMax": "The search term needs to be between {min} and {max} characters",
  "Label.Owner": "Owner",
  "Label.Admin": "Admin",
  "Label.Member": "Member",
  "Label.Guest": "Guest",
  "Message.Owner": "The community's owner.",
  "Message.Admin": "A community administrator.",
  "Message.Member": "A regular community member.",
  "Message.Guest": "A non-community member.",
  "Message.MaxNumberRoles": "A maximum of {maxRoles} roles are allowed.",
  "Message.PinLocked":
    "You cannot perform this action with a locked pin. Unlock your pin in the Account Settings page.",
  "Heading.GroupsYouOwn": "Communities You Own",
  "Heading.GroupsYouAreIn": "Communities You Are In",
  "Message.GroupRestricted": "This community is not available in your region",
  "Action.RequestToJoin": "Request to Join",
  "Heading.GroupSearchCategoryGameStudios": "Experience Studios",
  "Heading.GroupSearchCategoryGameDevelopment": "Experience Development",
  "Heading.GroupSearchCategoryFriends": "Friends' Communities",
  "Message.PayoutRestricted":
    "Your funds were recently transferred and are being verified. Please try again later.",
  "Message.UpdateRolesetRank":
    "{actor} updated roleset {roleSetName}'s rank from {oldRank} to {newRank}",
  "Message.UpdateRolesetDataNameOnly": "{actor} updated roleset {oldName}'s name to {newName}",
  "Message.UpdateRolesetDataDescOnly":
    '{actor} updated roleset {newName}\'s description from "{oldDescription}" to "{newDescription}"',
  "Message.UpdateRolesetData":
    '{actor} updated roleset {oldName}\'s name to {newName} and changed description from "{oldDescription}" to "{newDescription}"',
  "Action.SeeNewWallPosts": "See New Wall Posts",
  "Label.IndividualToGroupTotal":
    "Individual to Community Robux Transfers (includes pending transfers)",
  "Message.UserGroupPayoutIneligible":
    "User is new to community and not yet eligible for payouts. Please try again later.",
  "Message.LoadPayoutsError": "Unable to load payouts",
  "Label.AddFunds": "Add Funds",
  "Label.LastAddedFunds": "Successful transfer from {userName} to {groupName} on {transferDate}.",
  "Label.AddFundsPrompt": "Transfer from {userName} to {groupName}",
  "Message.AddFundsLimitMessage":
    "Transfers subject to holds. You can only transfer robux to this community from your account once every {limit} days",
  "Heading.AddFundsModal": "Transfer Funds",
  "Message.AddFundsModal": "Are you sure you want to transfer {robuxWithIcon} to {groupName}?",
  "Message.InsufficentFunds": "Insufficent Robux Funds",
  "Message.GeneralAddFundsError": "Something Went Wrong",
  "Action.MoreGroups": "More Communities",
  "Heading.Groups": "Communities",
  "Heading.MyGroups": "My Communities",
  "Label.SearchAllGroups": "Search All Communities",
  "Label.AddFundsAmount": "Amount",
  "Message.MaximumExceeded": "The maximum amount of Robux eligible to be transferred is {robux}",
  "Label.MembersCount": "{memberCount, plural, =0 {# Members} =1 {# Member} other {# Members}}",
  "Action.MyGroups": "My Communities",
  "Label.ConfigureGroupClothing": "Configure community clothing items",
  "Label.CreateGroupClothing": "Create community clothing items",
  "Label.CreateGroupGamesAndAssets":
    "Create and configure community experience and development items",
  "Label.AddPayoutRecipients": "Add Payout Recipients",
  "Action.GoToSettings": "Go to Settings",
  "Heading.TwoStepVerificationRequired": "Email Verification Required",
  "Message.TwoStepVerificationRequired":
    "2-Step Verification is required to make further transactions. Go to Settings > Security to complete 2-Step Verification.",
  "Heading.AddFunds": "Add Funds",
  "Message.TwoStepVerificationRequiredv2":
    "2-Step Verification is required to make further transactions. Go to your Security page to enable and complete 2-Step Verification via email.",
  "Action.GoToSecurity": "Go To Security",
  "Message.UpdateRecurringPayoutsError": "Unable to update recurring payouts.",
  "Message.TwoStepVerificationRequiredV3":
    "2-Step Verification is required to make further transactions. Go to your Security page to enable and complete 2-Step Verification via email.",
  "Heading.TwoStepVerificationRequiredV2": "Email Verification Required",
  "Message.ChangedGroupName":
    "{actor} changed the community name from {previousGroupName} to {currentGroupName}",
  "Heading.PreviousGroupNames": "Previous Community Names",
  "Label.PreviousGroupNames": "Previous community names",
  "Heading.ChangeGroupName": "Change Community Name",
  "Description.ChangeGroupNameCost": "Changing a community name will cost {robuxAmount}.",
  "Description.NewGroupName": "Enter the new community name",
  "Label.NewGroupName": "New community name",
  "Description.GroupNameChangeDetails":
    "I understand that once the community name has been changed:{listItemStart}it cannot be changed again for {numDays} days{listItemEnd}{listItemStart}community members will be notified of the change{listItemEnd}{listItemStart}the community will no longer be searchable under the previous name{listItemEnd}",
  "Message.GroupNameChangeInsufficientFunds":
    "Name change unsuccessful. You need {robuxAmount} more to change the community name.",
  "Message.CannotChangeToSameRole": "You cannot change a member's role to their same role.",
  "Message.MaximumNumberOfPayoutRecipients": "You can only pay out {numUsers} users at a time.",
  "Message.GroupMaxMemberLimitExceededError": "Community max member limit exceeded.",
  "Action.ShowLess": "Show Less",
  "Action.ReadMore": "Read More",
  "Heading.TwoStepVerificationRequiredV3": "2-Step Verification Required",
  "Message.TwoStepVerificationRequiredV4":
    "2-Step Verification is required to make further transactions. Go to your Security page to enable and complete 2-Step Verification.\t",
  "Message.LoadPreviousGroupNamesError": "Unable to load previous community names.",
  "Label.FilterGroups": "Filter Communities",
  "Label.SearchMyGroups": "Search My Communities",
  "Description.GroupNameChangeTerms":
    "I understand that once the community name has been changed:{listStart}{listItemStart}it cannot be changed again for {numDays} days{listItemEnd}{listItemStart}community members will be notified of the change{listItemEnd}{listItemStart}the community will no longer be searchable under the previous name{listItemEnd}{listEnd}",
  "Label.PreviousGroupName": "Previous community name",
  "Header.VerifiedEmailRequired": "Email Verification Required",
  "Description.VerifiedEmailRequired":
    "A verified email is required to change your communityâ€™s name. Please verify an email address in your account settings.",
  "Label.ChangeName": "Change Name",
  "Message.RecentOwnershipChange": "Community ownership was changed too recently.",
  "Message.NameChangeCooldown": "The name was changed too recently.",
  "Message.NameReuseCooldown": "The name was in use too recently.\t",
  "Heading.UnableToChangeName": "Unable to Change Name",
  "Description.ChangeNameCooldown":
    "Your community name was changed too recently.{lineBreak}You will be able to change your community name again in {numDays, plural, =0 {# days} =1 {# day} other {# days}}.",
  "Message.NotEnoughFundsNameChange":
    "You do not have enough funds to change your communities name.",
  "Label.AdministerCloudAuthentication": "Administer all community API keys",
  "Label.ManageCloudAuthentication": "Create community API keys",
  "Heading.OpenCloudPermissions": "Open Cloud",
  "Heading.GroupNameChangeSubject": "Community Name Changed: {previousGroupName}",
  "Description.GroupNameChangeBody":
    "{oldName} has been renamed to {newName}. You can visit the community here: {groupLink}",
  "Message.DistributeFundsError":
    "Unable to distribute funds. Please refresh and verify your funds before trying again.",
  "Label.ViewAnalytics": "View community experience analytics",
  "Message.AllyRequestSent": "Ally request sent to {group}",
  "Heading.GroupSearchCategoryClansGuilds": "Clans & Guilds",
  "Label.ImmersiveAdPayouts": "Immersive Ad Payouts",
  "Heading.Commissions": "Commissions",
  "Label.Commissions": "Commissions",
  "Action.SearchMyGroups": "Search my communities",
  "Label.CreateGroupDeveloperSubscriptionProduct":
    "Create Community Developer Subscription Product",
  "Message.CreateGroupDeveloperSubscriptionProduct":
    "{actor} created developer subscription product with id {id}",
  "Label.SubscriptionsPayoutReversals": "Payout Reversals",
  "Label.SubscriptionsPayouts": "Subscription Payouts",
  "Message.SavePlace": "{actor} saved place {game}",
  "Message.PublishPlace": "{actor} published place {game}",
  "Heading.Guilded": "Guilded",
  "Action.ViewCommunity": "View server",
  "Description.ConnectedChannel": "Connected to {spanStartBold}#{channelName}{spanEndBold}",
  "Label.ChangeChannel": "Change channel",
  "Label.UnlinkCommunity": "Unlink community",
  "Action.Unlink": "Unlink",
  "Description.LinkNewChannel": "Please link a new channel",
  "Action.LinkChannel": "Link channel",
  "Description.UnlinkCommunity":
    "Unlinking your community will remove it from Roblox.  You can still access your community on Guilded.  Are you sure you want to unlink?",
  "Heading.PostFirstAnnouncement": "Post your first Guilded announcement",
  "Description.PostFirstAnnouncement":
    "After you post your first announcement in Guilded, your announcement will show up here.",
  "Action.PostFirstAnnouncement": "Post your first announcement",
  "Heading.PublishingAdvanceRebates": "Publishing Advance Rebates\t",
  "Action.ViewAllAnnouncements": "View all Guilded announcements",
  "Label.PublishingAdvanceRebates": "Publishing Advance Rebates\t",
  "Heading.Announcements": "Announcements",
  "Description.SelectAnnouncementChannel":
    "Select an announcement channel to link to your community announcements.",
  "Description.CommunityDialogError":
    "An error occurred and we weren't able to complete that action. Please wait a moment and try again.",
  "Action.CreateAnnouncement": "Create Announcement",
  "Label.AcceptGuildedTerms":
    "I understand that I'm creating a Guilded account and consent to Guilded's {termsLinkStart}Terms of Service{termsLinkEnd} and {privacyLinkStart}Privacy Policy{privacyLinkEnd}.",
  "Description.CreatingGuildedAccount":
    "In order to create a server for your community on Guilded, we will need to create a Guilded account that will have your current Roblox account linked to it.",
  "Description.NameYourCommunity": "Enter a community name and we'll take care of the rest.",
  "Heading.ChangeAnnouncementChannel": "Change announcement channel",
  "Heading.CreateCommunity": "Create a server",
  "Description.SelectGuildedServer": "Select a Guilded community:",
  "Heading.AnnouncementsUpsell":
    "Supercharge your announcements with notifications, images, reactions and more",
  "Action.CreateCommunity": "Create a server",
  "Description.ConnectedTo": "Connected to",
  "Label.Channel": "channel",
  "Action.ContinueToGuilded": "Continue to Guilded",
  "Description.NoAnnouncementChannelsFound":
    "We couldn't find any announcement channels in your Guilded community. Go to Guilded to create one!",
  "Action.Retry": "Retry",
  "Heading.CommunityLinkSuccess": "{communityName} is now linked!",
  "Description.CommunityLinkSuccess":
    "Your Guilded server was successfully linked to your Roblox community. You can now post in your announcement channel to update your community announcement.",
  "Label.CreatingGuildedAccountAs": "Creating a Guilded account as",
  "Description.AlreadyHaveAGuildedAccount": "Already have a Guilded account?",
  "Action.LinkExistingCommunity": "Link an existing server",
  "Heading.LinkCommunity": "Link a community",
  "Heading.NotificationsUpsell": "Get notified when announcements are posted",
  "Description.AnnouncementsUpsell":
    "When you link your community to Guilded, announcements posted on Guilded will automatically post an announcement on your community",
  "Action.LinkCommunity": "Link existing server",
  "Description.GoToGuildedToLinkYourAccounts":
    "We're unable to find a Guilded account associated with your Roblox username. We'll walk you through the steps to get your Guilded and Roblox accounts connected.",
  "Label.ContinueAs": "Continue as",
  "Description.FetchedGuildedAccount":
    "To link a Guilded server, we’ve looked up your Roblox username on Guilded to find an associated account",
  "Action.Continue": "Continue",
  "Heading.CommunityDialogError": "Oops, something went wrong",
  "Label.CommunityName": "Community name",
  "Error.CommunityNameValidationTooShort": "Name is too short",
  "Description.NoGuildedServersFound":
    "We couldn't find any existing Guilded communities you have permission to link. You can create a new Guilded community instead!",
  "Label.GuildedAvatarAlt": "Guilded avatar image",
  "Action.NotifyMe": "Notify me",
  "Description.NotificationsUpsell":
    "Stay up to date with {groupName} by turning on notifications.",
  "Label.New": "New",
  "Action.TurnNotificationsOn": "Turn on notifications",
  "Action.TurnNotificationsOff": "Turn off notifications",
  "Label.ViewAnnouncements": "View community announcements",
  "Action.ShowMore": "Show More",
  "Heading.Community": "Community",
  "Label.JoinCommunityVisibility": "Show banner to join Guilded community",
  "Message.SubscribeToNotificationsError":
    "Unable to subscribe to community notifications. Please try again.",
  "Error.CommunityNameValidationInvalid": "Please try another name",
  "Message.NewFeaturesCollaboration":
    "We recently rolled out new group features for groups being used to collaborate on creation. If you're using this group to create content, {announceLinkStart}learn more here{announceLinkEnd} and stay up to date on these new features.",
  "Message.UnauthorizedToManageFeaturedContent":
    "You do not have permission to manage featured content for this community.",
  "Heading.Events": "Events",
  "Action.UnfeatureEvent": "Un-feature Event",
  "Action.FeatureEvent": "Feature Event",
  "Label.NoGroupEvents": "No events for now",
  "Message.FeatureEventSuccess": "Successfully featured the event.",
  "Message.UnfeatureEventSuccess": "Successfully un-featured the event.",
  "Label.CreateEvent": "Create event",
  "Label.GroupEventsCreatorHubUpsell":
    "Visit the Creator Hub to begin creating events for your members",
  "Label.GroupEventsUpsell": "Engage your community with events",
  "Label.CheckLaterForEvents": "Check back later for new events",
  "Label.EventDate": "{dayString} at {timeString}",
  NetworkError: "Something went wrong. Please try again later",
  "Message.NewFeaturesPayout":
    "We recently rolled out new payout features for groups, including overhauled design and the ability to set recurring payouts per experience. It is now recommended to go to {payoutLinkStart}Creator Hub{payoutLinkEnd} and manage your payouts there.",
  "Heading.Forums": "Forums",
  "Action.BanUser": "Ban user",
  "Message.TargetUserNotGroupBanned": "User is not banned from the community.",
  "Heading.Banned": "Banned",
  "Action.Ban": "Ban",
  "Label.SearchBannedUsers": "Search Banned Users",
  "Label.BanMembers": "Ban lower-ranked members",
  "Description.BanUserWarning":
    "Are you sure you want to ban this user? A banned user will not be able to join the community.",
  "Heading.BanUserWarning": "Warning",
  "Label.BannedBy": "Banned by",
  "Message.UnbanUserError": "Failed to unban user",
  "Message.UnbanUserSuccess": "Successfully unbanned user",
  "Action.UnbanMember": "Unban user",
  "Action.RemoveContent": "Remove Content",
  "Action.KickUser": "Kick user",
  "Action.Kick": "Kick",
  "Description.KickUserWarning":
    "Are you sure you want to kick this user? Kicking a user will remove the user from the community.",
  "Message.BanMember": "{actor} banned user {user}",
  "Message.UnbanMember": "{actor} unbanned user {user}",
  "Label.BanMember": "Ban user",
  "Label.UnbanUser": "Unban user",
  "Label.NoBannedUsers": "No users are banned from this community",
  "Message.BanUserError": "Failed to ban user",
  "Message.RemoveContentSuccess": "Successfully removed the content of the user",
  "Message.BanUserSuccess": "Successfully banned user",
  "Action.UnbanUser": "Unban user",
  "Message.BuildBanListError": "Unable to load the community ban list.",
  "Message.BannedFromGroup": "You have been banned from this community.",
  "Action.Save": "Save",
  "Action.AddForumCategory": "Add category",
  "Description.AddForumCategory": "Forum categories are where members can post and reply to topics",
  "Label.ForumCategoryName": "Category Name",
  "Label.ForumCategoryDescription": "Forum category description",
  "Heading.EditForumCategory": "Edit Forum Category",
  "Description.ForumCategoryNameExamples": "Ex. Updates, Announcements, Support etc.",
  "Label.ForumCategoryNamePlaceholder": "Write your Forum category name",
  "Label.ForumCategoryDescriptionPlaceholder": "Write your Forum category description",
  "Description.ForumCategories":
    "Forum categories are a place for your community to discuss posts. You can add as many forum categories as you like. You can manage permissions for forums here",
  "Heading.DeleteConfirmation": "Delete confirmation",
  "Description.DeleteForumCategory":
    "Are you sure you want to delete the category '{forumCategoryName}'? Your members will no longer be able to see the category. You cannot undo this action later",
  "Error.ForumCategoryNameValidationTooShort": "Name is too short",
  "Error.ForumCategoryDescriptionValidationTooShort": "Description too short",
  "Error.DeleteForumCategoryNameValidationNotEqual": "Name does not match",
  "Label.GroupAffiliatePayouts": "Community Affiliate Payouts",
  "Label.DisableDeleteLastCategory": "Cannot delete last Forum category",
  "Description.MaxNumberOfCategoriesReached": "{maxNumberOfCategories} category limit reached",
  "Action.ArchiveForumCategory": "Archive category",
  "Label.GeneralDiscussions": "General Discussions",
  "Action.Rename": "Rename",
  "Action.Archive": "Archive",
  "Action.DeleteForumCategory": "Delete Category",
  "Label.Feedback": "Feedback",
  "Action.RenameForumCategory": "Rename Category",
  "Description.ArchiveForumCategory":
    "Are you sure you want to archive the category '{forumCategoryName}'? Your members will no longer be able to see the category. You can undo this action later",
  "Label.HelpAndSupport": "Help and Support",
  "Action.GetStarted": "Get Started",
  "Heading.ForumsUpsell": "Add Forums to your community",
  "Description.ForumsUpsell":
    "Forums are a place for your community to post and reply to discussions",
  "Action.Add": "Add",
  "Action.UnarchiveForumCategory": "Unarchive Category",
  "Action.Unarchive": "Unarchive",
  "Description.UnarchiveForumCategory":
    "Are you sure you want to unarchive the category '{forumCategoryName}'? Your members will be able to see the category again. You can undo this action later",
  "Heading.ArchivedCategories": "Archived Categories",
  "Error.CategoryNameInappropriateContent":
    "Your category name does not meet our moderation standards. Please revise and try posting again.",
  "Message.PermissionsMovingToCH":
    "We’ll be moving these permissions to Creator Hub. Any changes to these in Roblox.com may be deprecated in the future.",
  "Heading.NewFeaturesCH": "New Features in Creator Hub",
  "Message.GroupFeaturesInCreatorHub":
    "We've rolled out new group features for collaboration on creation! {linkStart}Click here{linkEnd} to learn more.",
  "Heading.AssetsMovingToCH": "Asset permissions moving to Creator Hub",
  "Label.SubscribeToPost": "Subscribe to post",
  "Error.LoadCategoryTitle": "Unable to load Forums",
  "Error.ReloadingSubtitle": "Something went wrong, try reloading",
  "Action.RetryLoadingForums": "Retry Loading Forums",
  "Action.RetryLoadingPosts": "Retry loading posts",
  "Label.NoPostsFoundHeader": "Make the first post",
  "Label.NoPostsFoundText": "Be the first to start a discussion",
  "Label.Replies": "replies",
  "Label.EditPost": "Edit post",
  "Label.LockPost": "Lock post",
  "Label.CopyLink": "Copy link",
  "Label.ReportPost": "Report Post",
  "Label.PinPost": "Pin post",
  "Label.UnpinPost": "Unpin post",
  "Label.UnlockPost": "Unlock post",
  "Action.LearnMore": "Learn More",
  "Label.LinkCopied": "Link copied",
  "Action.ConfigureInHub": "Configure in Hub",
  "Error.CopyLink": "Could not copy the link",
  "Action.GoToCreatorHub": "Go to Creator Hub",
  "Action.CreatePost": "Create post",
  "Label.NoCommentsFoundHeader": "Make the first comment",
  "Label.NoCommentsFoundText": "Be the first to start a discussion",
  "Label.WriteComment": "Write a comment",
  "Action.Reply": "Reply",
  "Action.ShowMoreReplies": "Show More Replies",
  "Label.PostContent": "Post Content",
  "Label.PostTitle": "Post Title",
  "Label.WriteSomething": "Write something...",
  "Label.Title": "Title",
  "Action.EditPost": "Edit Post",
  "Error.ForumPostModerated":
    "Your post does not meet Roblox moderation standards. Please revise and try posting again.",
  "Label.ReplyingTo": "Replying to",
  "Error.LoadPostTitle": "Unable to load post",
  "Action.RetryLoadingPost": "Retry Loading Post",
  "Error.LoadCommentsTitle": "Unable to load comments",
  "Error.LoadRepliesTitle": "Unable to load replies",
  "Action.RetryLoadingComments": "Retry Loading Comments",
  "Action.RetryLoadingReplies": "Retry Loading Replies",
  "Action.ShowReplies": "Show Replies",
  "Error.CommentModerationFailed":
    "Your comment does not meet our moderation standards. Please revise and try posting again.",
  "Label.CreateForumPosts": "Create posts",
  "Heading.ForumsPermissions": "Forums",
  "Label.ManageForumCategories": "Manage categories",
  "Label.RemoveForumPosts": "Remove posts",
  "Label.LockForumPosts": "Lock posts",
  "Label.PinForumPosts": "Pin posts",
  "Label.RemoveForumComments": "Remove comments",
  "Label.CreateForumComments": "Create comments",
  "Label.EditReply": "Edit reply",
  "Label.EditComment": "Edit comment",
  "Label.DeleteReply": "Delete reply",
  "Label.DeleteComment": "Delete comment",
  "Label.ReportAbuse": "Report abuse",
  "Heading.GroupWallDeprecated": "Community wall is now read-only",
  "Description.GroupWallDeprecated": "Start posting in Forums!",
  "Action.VisitForums": "Visit Forums",
  "Action.Back": "Back",
  "Label.Reply": "reply",
  "Message.CannotJoinGroup": "You do not have permission to join this community.",
  "Heading.GroupForumsEarlyAccess": "Welcome to Forums Early Access",
  "Description.GroupForumsEarlyAccess":
    "Note: You may encounter bugs or unfinished features. Thank you for trying it out!",
  "Label.BlockUser": "Block user",
  "Label.SubscribeToComment": "Subscribe to Comment",
  "Label.UnsubscribeFromPost": "Unsubscribe from Post",
  "Label.UnsubscribeFromComment": "Unsubscribe from Comment",
  "Message.NotificationPreferenceUpdated": "Successfully updated your notification preference.",
  "Action.BlockUser": "Block",
  "Description.BlockUserFooterDialog":
    "You won't be able to see their posts or contact each other.",
  "Description.BlockUserWarning": "Are you sure you want to block this user?",
  "Message.BlockUserSuccess": "You have successfully blocked a user.",
  "Label.AnnouncementsNotificationPreference": "Announcements",
  "Label.RepliesNotificationPreference": "Replies",
  "Label.CommentsNotificationPreference": "Comments",
  "Description.AnnouncementsNotificationPreference": "A community publishes an announcement",
  "Description.CommentsNotificationPreference": "Someone comments on your post",
  "Description.RepliesNotificationPreference": "Someone replies to your comment",
  "Heading.BlockUserWarning": "Warning",
  "Label.PostCreated": "Your post has been created.",
  "Label.FormerMember": "Former Member",
  "Action.Submit": "Submit",
  "Description.NoPostPermission": "You do not have permission to post",
  "Description.NoReplyPermission": "You do not have permission to reply",
  "Action.Comment": "Comment",
  "Description.NoReplyLocked": "You cannot reply to a locked post",
  "Label.LockedForumPost": "This post is locked",
  "Message.LockedForumPostComment": "You cannot comment on a forum post that is locked",
  "Label.EditedMarker": "(edited)",
  "Description.LeaveGroupAsOwnerConfirm":
    "Leaving communities you own without assigning a new owner may result in disruptions for the community. Would you like to change owners before leaving?",
  "Label.ChangeOwnerQuestion": "Change Owner?",
  "Message.CreateForumCategory": "{actor} created Forum Category {category}",
  "Message.UpdateForumCategory": "{actor} updated Forum Category {oldName}'s name to {newName}",
  "Message.DeleteForumCategory": "{actor} deleted Forum Category {category}",
  "Message.UnarchiveForumCategory": "{actor} unarchived Forum Category {category}",
  "Message.ArchiveForumCategory": "{actor} archived Forum Category {category}",
  "Message.DeleteRolesetLog": "{actor} deleted roleset {rolesetName}",
  "Message.CreateRolesetLog": "{actor} created roleset {rolesetName}",
  "Error.ForumPostTitleValidationTooShort": "Title is too short",
  "Error.ForumPostContentValidationTooShort": "Content is too short",
  "Error.ForumCommentContentValidationTooShort": "Content is too short",
  "Error.ForumContentValidationMinLength": "Content is too short",
  "Error.ForumTitleValidationMinLength": "Title is too short",
  "Heading.ConfigureCommunity": "Configure Community",
  "Action.SeeWall": "See Wall",
  "Message.KickUserSuccess": "Successfully kicked user",
  "Message.KickUserError": "Failed to kick user",
  "Label.SyncRolesToGuildedCommunityConflictError":
    "This Guilded server is already role synced to a different community.",
  "Label.SyncRolesToGuildedCommunity": "Enable roles to be synced to this Guilded server",
  "Description.JoinCommunityFirst": "You need to join the community first",
  "Message.CreateCommerceProduct": "{actor} created a commerce product with ID {id}",
  "Message.SetCommerceProductActive": "{actor} put a commerce product on sale. Product ID: {id}",
  "Message.ArchiveCommerceProduct": "{actor} archived a commerce product with ID {id}",
  "Message.AcceptCommerceProductBundlingFee":
    "{actor} has accepted the bundling fee for a commerce product with ID {id}",
  "Message.SetCommerceProductInactive":
    "{actor} took a commerce product off sale. Product ID: {id}",
  "Message.RejectCommerceProductBundlingFee":
    "{actor} has rejected the bundling fee for a commerce product with ID {id}",
  "Heading.GroupForumsTopPosts": "Top Community Posts",
  "Heading.SocialMedia": "Social Media",
  "Action.Follow": "Follow",
  "Action.Unfollow": "Unfollow",
  "Heading.Followers": "Followers",
  "Message.FollowSuccess": "Now following {name}",
  "Heading.Follower": "Follower",
  "Message.ConnectShopifyStore": "{actor} connected the Shopify Store {shopifyShopDomain}",
  "Message.DisconnectShopifyStore": "{actor} disconnected the Shopify Store {shopifyShopDomain}",
  "Message.PaidServicesEnabled":
    "Group ownership transfer is disallowed because Extended Services are enabled or there is an unpaid balance associated with them.",
  "Label.Following": "Following",
  "Label.Joined": "Joined",
  "Label.NoBioYet": "No bio yet.",
  "Action.More": "more",
  "Label.PreviousNames": "Previous names",
  "Message.UnfollowError": "Unable to unfollow.",
  "Heading.ContentModeration": "Content Moderation",
  "Heading.KeywordBlocklist": "Blocked Words",
  "Label.ManageKeywordBlockList": "Manage blocked words",
  "Label.ViewKeywordBlockList": "View blocked words",
  "Heading.ContentModerationPermissions": "Content Moderation",
  "Heading.SocialLinksNew": "Social links",
  "Description.KeywordBlockList":
    "Posts and replies containing words or phrases on this list will be automatically hidden or blocked in this Community.",
  "Heading.AddWordToBlockList": "Add word or phrase",
  "Heading.ActiveList": "Active List ({count})",
  "Error.WallPostKeywordMatched":
    "Your post contains content not allowed on this Community. Please revise and try posting again.",
  "Label.AddKeywordBlockListPlaceholder": "Enter word or phrase",
  "Action.Edit": "Edit",
  "Label.Owned": "Owned",
  "Message.NoGroupsFound": "No communities found.",
  "Message.NotInAnyGroups": "You are not a member of any communities.",
  "Error.CreateKeywordModerated":
    "One or more of your words may not show up in the list as they are already blocked by Roblox",
  "Message.KeywordsAdded": "{count} words added.",
  "Message.KeywordsAddedNoKeywords": "Word(s) already exist. No new words added.",
  "Error.LoadBlockedKeywordsTitle": "Error loading words",
  "Message.NoBlockedKeywordsTitle": "No words found",
  "Action.RetryLoadingKeywords": "Retry loading words",
  "Error.EditKeywordModerated": "Oops! This word can't be used because Roblox already blocks it",
  "Message.InvalidKeywords": "One or more words are invalid.",
  "Message.InvalidKeywordId": "KeywordId is invalid.",
  "Message.InvalidRequest": "Invalid request.",
  "Message.NotFound": "Not found",
  "Message.Conflict": "There was a conflict in your request.",
  "Error.EditKeywordInvalidRequest": "The word is invalid and cannot be edited",
  "Error.CreateKeywordInvalidRequest": "One or more words are invalid and cannot be added",
  "Error.EditKeywordConflict": "A word with the same text already exists",
  "Message.KeywordEdited": "Word edited",
  "Message.KeywordDeleted": "Word deleted",
  "Label.VotePercent": "{percent} liked",
  "Description.ForumsReplacesWallNotice":
    "Members will not be able to post to your Wall when Forums are enabled.",
  Videos: "Videos",
  "Heading.Videos": "Videos",
  "Description.ForumsRolesLink": "Set top-level permissions for your Forums in Roles",
  "Label.Videos": "Videos",
  "Message.NoBlockedKeywordsSubtitle": "Add one or more words above",
  "Error.CreateKeywordEmpty": "One or more words are empty.",
  "Error.CreateKeywordCannotBeOnlyWildcard": "Words cannot consist of only formatting characters",
  "Error.CreateKeywordTooLong":
    'Word "{keyword}" exceeds maximum length of {maxLength} characters.',
  "Message.KeywordAdded": "Word added",
  "Description.KeywordBlocklistMatching":
    "Blocked Words use exact matches. For partial matches, include an ({wildcard}) at the beginning or end of a keyword.",
  "Label.MembersCountAbbreviated":
    "{membersCount, plural, =0 {{membersCountAbbreviated} members} =1 {{membersCountAbbreviated} member} other {{membersCountAbbreviated} members}}",
  "Label.VerificationNone": "None",
  "Label.VerificationLevel": "Verification Level",
  "Label.VerificationLow": "Low",
  "Label.VerificationMedium": "Medium",
  "Label.VerificationHigh": "High",
  "Description.VerificationNone": "Users do not require account verification before joining",
  "Description.VerificationLow": "Users must be phone, email, or ID verified before joining",
  "Description.VerificationMedium":
    "Users must be ID verified, or phone and email verified before joining",
  "Description.VerificationHigh": "Users must be ID verified before joining",
  "Error.CreateKeywordTooShort": 'Word "{keyword}" is below the minimum length of {minLength}.',
  "Error.EditKeywordEmpty": "Word cannot be empty",
  "Description.KeywordBlocklistMatching2":
    "Separate words and phrases with a comma to add up to {limit} at a time.",
  "Error.ContentReloadingSubtitle": "Something went wrong while loading more content.",
  "Action.TryAgain": "Try again",
  "Heading.GroupSearchCategoryConnections": "Connections' Communities",
  "Action.LearnMoreLink": "Learn more.",
  "Action.VerifyMyAccount": "Verify My Account",
  "Heading.VerificationRequired": "Account Verification Required",
  "Label.DeleteForumCategory": "Delete Forum Category",
  "Label.DeleteForumPost": "Delete Forum Post",
  "Label.DeleteForumComment": "Delete Forum Comment",
  "Modal.ContentTextMedium":
    "Verify your account to join this community.\n\n1. Go to Account Info\n2. Choose one verification option:\n    - Add Phone AND Add Email\n    - Verify My Age\n3. Complete the verification process",
  "Modal.ContentTextHigh":
    "Verify your account to join this community.\n\n1. Go to Account Info > Verify My Age\n2. Complete the verification process",
  "Modal.ContentTextLow":
    "Verify your account to join this community.\n\n1. Go to Account Info\n2. Choose one verification option:\n    - Add Phone\n    - Add Email\n    - Verify My Age\n3. Complete the verification process",
  "Message.DeleteForumPost": "{actor} deleted forum post by user {user}",
  "Message.DeleteForumComment": "{actor} deleted forum comment by user {user}",
  "Description.CategoryArchived": "This category is archived",
  "Description.PostArchived": "This post is archived",
  "Label.ViewForums": "View forums",
  "Description.GroupWallDeprecatedNoForums":
    "Forums are now available! Ask your community owner for details",
  "Heading.GroupWallDeprecatedNoForums": "Community wall is now read-only",
  "Label.AccountTenure": "Account Age",
  "Label.TenureNone": "No Restriction",
  "Label.TenureDays": "{numDays, plural, =1 {{numDays} Day} other {{numDays} Days}}",
  "Description.AccountTenureRequirementExplanation":
    "Only accounts created more than the selected number of days ago can join.",
  "Description.RequiresAccountTenureTooltip":
    "You must have an account for {numDays, plural, =1 {{numDays} day} other {{numDays} days}} before joining this community.",
  "Label.CommunityCreatorRewards": "Community Creator Rewards",
  "Label.CommunityAudienceExpansionPayouts": "Community Audience Expansion Payouts",
  "Label.FollowersCountAbbreviated":
    "{followersCount, plural,  \n  =1 {{followersCountAbbreviated} follower} \n   other {{followersCountAbbreviated} followers}\n}",
  "Action.Chat": "Chat",
  "Action.AddConnection": "Add",
  "Action.RemoveConnection": "Remove",
  "Action.Pending": "Pending",
  "Action.AcceptRequest": "Accept",
  "Label.MembersList": "Members list",
  "Heading.ManageCollaboratorsCH": "Manage your collaborators in Creator Hub",
  "Message.ManageCollaboratorsInCreatorHub":
    "We have improved permissions and membership management within Creator Hub and recommend you head there if you want to manage collaborators.",
  "Heading.PermissionsMovedToCH": "Creator permissions moved to Creator Hub",
  "Message.PermissionsMovedToCH":
    "We have moved the below permissions to Creator Hub. The new system is more granular, and we strongly recommend using it instead of the deprecated permissions below.",
  "Heading.ChangeRole": "Change from '{oldRole}' to '{newRole}'",
  "Message.LowerRankedRole":
    "{username} will have a lower ranked Community role, but may still have access due to their access in the new {linkStart}creation permissions system{linkEnd}.",
  "Action.ChangeRole": "Change role",
  "Message.PinForumPost": "{actor} pinned forum post by user {user}",
  "Message.UnpinForumPost": "{actor} unpinned forum post by user {user}",
  "Message.LockForumPost": "{actor} locked forum post by user {user}",
  "Message.UnlockForumPost": "{actor} unlocked forum post by user {user}",
  "Label.MembersCountAbbreviatedOptionalCapitalization":
    "{membersCount, plural,  \n  =1 {{membersCountAbbreviated} {capitalize, select, true {Member} other {member}}} \n   other {{membersCountAbbreviated} {capitalize, select, true {Members} other {members}}}\n}",
  "Label.FollowersCountAbbreviatedOptionalCapitalization":
    "{followersCount, plural,  \n  =1 {{followersCountAbbreviated} {capitalize, select, true {Follower} other {follower}}} \n   other {{followersCountAbbreviated} {capitalize, select, true {Followers} other {followers}}}\n}",
  "Label.PinForumPost": "Pin Forum Post",
  "Label.UnpinForumPost": "Unpin Forum Post",
  "Label.LockForumPost": "Lock Forum Post",
  "Label.UnlockForumPost": "Unlock Forum Post",
  "Description.AnnouncementsOnlyOneLinkedServerAlert":
    "A Guilded server can now only be connected to one Roblox community.",
  "Label.Search": "Search",
  "Label.ChooseRole": "Choose Role",
  "Heading.NameOrAssetsOrDescription": "Name, Icon, Cover Photo or Description",
  "Label.SlowMode.Slower": "Slower",
  "Label.SlowMode.Disabled": "Disabled",
  "Label.SlowMode.Slow": "Slow",
  "Label.SlowMode.Slowest": "Slowest",
  "Description.SlowMode.Disabled": "Default rate limits for community activity.",
  "Description.SlowMode.Slow": "1 post per 2 minutes, 2 comments per minute.",
  "Description.SlowMode.Slower": "1 post per 5 minutes, 1 comment per minute.",
  "Description.SlowMode.Slowest": "1 post per 10 minutes, 1 comment per 2 minutes.",
  "Heading.ActivitySettings": "Activity Settings",
  "Label.SlowMode": "Slow Mode",
  "Message.SettingsSaved": "Settings saved successfully",
  "Message.SettingsSaveFailed": "Failed to save settings. Please try again.",
  "Label.PostDeleted": "Post deleted",
  "Label.PostLocked": "Post locked",
  "Label.PostPinned": "Post pinned",
  "Label.PostUnpinned": "Post unpinned",
  "Label.PostUnlocked": "Post unlocked",
  "Action.AddRole": "Add a role",
  "Description.ForumCategoryPermissions":
    "Category permissions will overrule Community permissions within the given Category",
  "Header.ForumCategoryPermissions": "Forum Category Permissions",
  "Action.RemoveRole": "Remove role",
  "Message.LeaveGroup": "{actor} left",
  "Message.UpdateGroupIcon": "{actor} updated icon",
  "Message.UpdateCoverPhoto": "{actor} updated cover photo",
  "Error.RetryAfterSeconds":
    "Slow Mode enabled. Please wait {seconds} seconds before sending again.",
  "Message.GroupCoverPhotoMissing": "Cover photo is missing.",
  "Message.GroupCoverPhotoInvalid": "Cover photo file format or dimensions are invalid.",
  "Label.CreateGroupCoverPhoto": "Cover Photo",
  "Description.UpdateGroupCoverPhoto":
    "Cover photo must be one of the available dimensions: {dimensions}",
  "Label.BypassSlowMode": "Bypass slow mode",
  "Label.Content": "Content",
  "Label.Image": "Image",
  "Description.SlowMode":
    "Members will be restricted to sending fewer posts, comments, and replies in Community Forums. When set to Disabled, default rate limits apply.",
  "Label.ManageContentModeration": "Manage content moderation",
  "Label.ViewContentModeration": "View content moderation",
  "Label.ManageForumCategory": "Manage category",
  "Message.JoinGroup": "{actor} joined",
  "Action.EditAnnouncement": "Edit Announcement",
  "Action.DeleteAnnouncement": "Delete Announcement",
  "Message.CannotUpdateMembershipRelationshipRank": "Cannot update membership rank.",
  "Action.Create": "Create",
  "Label.NoAnnouncements": "No announcements yet...",
  "Message.AnnouncementDeleteFail": "Failed to delete announcement.",
  "Message.AnnouncementDeleteSuccess": "Announcement successfully deleted.",
  "Message.AnnouncementUpdateSuccess": "Announcement updated.",
  "Message.AnnouncementUpdateFail": "Error updating announcement.",
  "Label.AnnouncementProcessing": "Your post is being processed and will complete soon",
  "Action.VisitCategories": "Visit Categories",
  "Description.CategoryPermissionsUpsell":
    "You can now set permissions specific to a Forum category",
  "Action.VisitRoles": "Visit Roles",
  "Label.UpdateGroupIcon": "Update Icon",
  "Label.UpdateGroupCoverPhoto": "Update Cover Photo",
  "Error.AnnouncementTitleValidationMinLength": "Title is too short",
  "Error.AnnouncementContentValidationMinLength": "Content is too short",
  "Message.GroupCoverPhotoTooLarge": "Cover photo cannot be larger than {maxSize} MB.",
  "Message.GroupCoverPhotoUpdateFail": "Unable to update community cover photo",
  "Message.GroupCoverPhotoUpdateSuccess": "Successfully updated community cover photo",
  "Message.GroupCoverPhotoDeleteFail": "Unable to delete community cover photo",
  "Message.GroupCoverPhotoDeleteSuccess": "Successfully deleted community cover photo",
  "Message.GroupIconUpdateFail": "Unable to update community icon",
  "Message.GroupIconUpdateSuccess": "Successfully updated community icon",
  "Message.GroupDescriptionUpdateSuccess": "Successfully updated community description",
  "Message.GroupDescriptionUpdateFail": "Unable to update community description",
  "Label.NameGroup": "Name",
  "Message.DescriptionModerated": "The description is moderated.",
  "Error.AnnouncementModerated":
    "Your announcement does not meet Roblox moderation standards. Please revise and try posting again.",
  "Message.GracefulDegradation":
    "Whoa, it's busy in here! We're showing a simplified profile to keep things running smoothly. Please check back later to see the full view.",
  "Message.GracefulDegradationTitle": "Communities Features Reduced",
  "Label.MemberListVisible": "Community member list publicly visible",
  "Message.GracefulDegradationCommunities":
    "Due to high traffic, we're showing a simplified community space. Check back later for the full view.",
  "Label.MemberCapitalPlural": "Members",
  "Label.FollowerCapital": "Follower",
  "Label.FollowerCapitalPlural": "Followers",
  "Label.Follower": "follower",
  "Label.FollowerPlural": "followers",
  "Label.MemberLowerCase": "member",
  "Label.MemberLowerCasePlural": "members",
  "Label.PostAnnouncements": "Create community announcements",
  "Action.Move": "Move",
  "Message.CategoriesOrderSuccess": "Categories successfully ordered.",
  "Message.UpdateSecuritySettings": "{actor} updated the security settings",
  "Label.AllRoles": "All Roles",
  "Action.AddRoles": "Add roles",
  "Label.CurrentRoles": "Current roles",
  "Heading.MembersListEducationalTooltip": "Members list moved",
  "Label.MembersListEducationalTooltip": "You can now view it here",
  "Label.CustomizeName": "Customize Name",
  "Action.Unblock": "Unblock",
  "Action.JoinExperience": "Join",
  "Message.SendConnectionRequestError": "Unable to send connection request.",
  "Message.AcceptFriendRequestError": "Unable to accept friend request.",
  "Message.RemoveFriendError": "Unable to unfriend user.",
  "Error.FailedToJoinExperience": "Failed to join experience. Please try again.",
  "Action.LogInToAddConnection": "Sign in to add",
  "Action.SignUpToAddConnection": "Sign up to add",
  "Action.EditProfile": "Edit Profile",
  "Action.EditAvatar": "Edit Avatar",
  "Message.BlockRequestError": "Unable to block user.",
  "Heading.GroupShoutDeprecated": "Shouts retire on January 30",
  "Description.GroupShoutDeprecated":
    "Announcements are the new way to share updates with your community. Try posting one now!",
  "Heading.GroupShoutDeprecatedV2": "Shouts retire on February 27",
  "Heading.GroupWallDeprecatedV2": "Walls are read-only and will be retired end of March",
  "Label.HideCommentConfirmation": "Are you sure you want to hide this comment?",
  "Action.Hide": "Hide",
  "Label.HidePostConfirmation": "Are you sure you want to hide this post?",
  "Description.HidePostConfirmationFooter": "You will no longer be able to see this post.",
  "Response.PostHidden": "Post hidden successfully.",
  "Description.HideCommentConfirmationFooter": "You will no longer be able to see this comment.",
  "Response.CommentHidden": "Comment hidden successfully.",
  "Action.HideComment": "Hide comment",
  "Action.HidePost": "Hide post",
  "Action.ViewDetails": "View details",
  "Description.AgeAssuranceUpsell": "Get yours done now to stay in the conversation",
  "Heading.AgeAssuranceUpsell": "An age check will soon be required to post",
  "Countdown.TwoOrMoreDaysLeft": "{count} days left",
  "Countdown.OneDayLeft": "1 day left",
  "Countdown.ZeroDaysLeft": "0 days left",
  "Label.SendAnnouncementNotifications": "Send notification to all members.",
  "Label.AssignRole": "Assign Role",
  "Message.AssignRole": "{actor} assigned roleset {rolesetName} to {user}",
  "Label.UnassignRole": "Unassign Role",
  "Message.UnassignRole": "{actor} unassigned roleset {rolesetName} from {user}",
  "Heading.Permissions": "Permissions",
  "Message.BaseMemberRoleInfo":
    "We added a new base member role. Every member of your community is automatically assigned the base member role and all its permissions. Any changes to permissions of the base member role extend to all members.",
  "Heading.MultiRolesUpsell": "NEW: Assign multiple roles per member!",
  "Message.MultiRolesUpsell":
    "Layer permissions and create custom vanity roles to organize your community exactly how you want",
  "Heading.CheckAgeInfo": "Let's check your age",
  "Description.CheckAgeInfo":
    "Complete this quick step to unlock posting, commenting, and replying in forums",
  "Heading.AgeCheck": "You need to complete an age check before you can post",
  "Description.AgeCheck":
    "It just takes a quick second. Then you can jump straight into the conversation",
  "Error.ForumContentValidationMaxLength": "Content is too long",
  "Error.AnnouncementContentValidationMaxLength": "Content is too long",
  "Message.CannotUpdateMemberRoleSetColor": "Cannot update Member role color.",
  "Label.Group": "Group",
  "Message.SendFriendRequestError": "Unable to send friend request.",
  "Heading.RoleColor": "Role Color",
  "Message.AgeIneligible": "Age requirements not met to complete the request.",
  "Message.AgeVerificationRequired": "Age verification is required to complete the request.",
  "Heading.YourRoles": "Your roles",
  "Label.RoleName": "Name",
  "Message.RoleCreateSuccess": "Role successfully created.",
  "Label.RoleColorDefault": "Default",
  "Label.RoleColorRed": "Red",
  "Label.RoleColorCrimson": "Crimson",
  "Label.RoleColorOrange": "Orange",
  "Label.RoleColorRust": "Rust",
  "Label.RoleColorYellow": "Yellow",
  "Label.RoleColorPistachio": "Pistachio",
  "Label.RoleColorGreen": "Green",
  "Label.RoleColorTeal": "Teal",
  "Label.RoleColorTurquoise": "Turquoise",
  "Label.RoleColorBlue": "Blue",
  "Label.RoleColorMidnight": "Midnight",
  "Label.RoleColorPurple": "Purple",
  "Label.RoleColorLavender": "Lavender",
  "Label.RoleColorMagenta": "Magenta",
  "Label.RoleColorPlum": "Plum",
  "Label.RoleColorPink": "Pink",
  "Message.RoleCreateFail": "Role creation failed. Please try again.",
  "Message.RoleWithUsersAllowDeletion":
    "There {amount, plural, =0 {are # users} =1 {is # user} other {are # users}} in this role. Removing it may result in a loss of permissions for those users. Do you want to continue to delete {role}?",
  "Label.NewestToOldest": "Newest to oldest",
  "Label.OldestToNewest": "Oldest to newest",
  "Message.AcceptAllSuccess": "All join requests have been accepted.",
  "Message.DeclineAllSuccess": "All join requests have been declined.",
  "Heading.Analytics": "Analytics",
  "Label.ExperienceServers": "Servers for {experience}",
  "Action.Refresh": "Refresh",
  "Message.DeleteRoleWithUsersAutoAssignWarning":
    "There {amount, plural, =0 {are # users} =1 {is # user} other {are # users}} in this role. Removing it may result in a loss of permissions for those users.  After you delete it, new members will be assigned the base member role only. Do you want to continue to delete {role}?",
  "Message.DeleteRoleAutoAssignWarning":
    "New members will be assigned the base member role only. Are you sure you want to delete {role}?",
  "Heading.GroupAnalyticsGoToCreatorHub": "See more in your new Community analytics dashboard",
  "Description.GroupAnalyticsGoToCreatorHub":
    "Head to Creator Hub to go beyond the basics. Drill down into metrics and explore interactive graphs to get the full story.",
  "Action.View": "View",
  "Heading.CommunityVisits": "Community visits",
  "Heading.ForumPostViews": "Post views",
  "Heading.ForumComments": "Comments",
  "Heading.ForumPostsCreated": "Posts created",
  "Action.Last7Days": "Last 7 Days",
  "Action.Last28Days": "Last 28 Days",
  "Action.Last90Days": "Last 90 Days",
  "Action.Last365Days": "Last 365 Days",
  "Label.UpdateGroupSecuritySettings": "Update Security Settings",
  "Label.ViewCommunityAnalytics": "View community analytics",
  "Action.SaveDraft": "Save Draft",
  "Action.Publish": "Publish",
  "Label.LegacyOwnerRoleSet": "Role 255",
  "Message.UpdateSecuritySettingsVerificationLevel":
    "{actor} changed the verification level requirement",
  "Message.UpdateSecuritySettingsAccountTenure": "{actor} changed the account age requirement",
  "Message.UpdateSecuritySettingsSlowmode": "{actor} changed the slowmode requirement",
  "Message.UpdateSecuritySettingsMemberListVisibility":
    "{actor} changed the member list visibility",
  "Action.NewPosts": "New Posts",
  "Action.NewComments": "New Comments",
  "Action.RemovePoll": "Remove",
  "Message.Saved": "Saved",
  "Message.OwnerRolesetDeprecation":
    "Community owners are now granted all permissions automatically instead of requiring a special role. You can create, edit, reassign, and delete roles with rank 255.",
  "Heading.OwnerRolesetDeprecation": "Roles with rank 255 no longer have ownership privileges.",
  "Label.RoleRestrictedToggle": "Role-restricted (Age-checked 16+)",
  "Description.RoleRestrictedToggle": "Only members with the required role(s) can participate.",
  "Label.RoleRestrictedAgeGate": "Must be age verified 16+ to restrict categories",
  "Header.AddRoles": "Add roles",
  "Description.AddRoles":
    "Only roles you assign to this category will be able to view it when the restrict toggle is enabled",
  "Message.CreatedAnnouncement": '{actor} created an announcement "{title}"',
  "Message.DeletedAnnouncement": '{actor} deleted an announcement "{title}"',
  "Description.RoleRestrictedCategory": "This a role restricted category",
  "Description.AgeRestrictedCategoryIneligible":
    "Your account does not meet the minimum age requirement for this category.",
  "Heading.AgeRestrictedCategory": "Restricted access",
  "Description.AgeRestrictedCategoryEligible":
    "This category is marked as age restricted. Do you wish to proceed?",
  "Heading.RoleRestrictedCategory": "Role restricted category",
  "Description.RoleRestrictedCategoryRolesList":
    "Only the following roles have access to this category",
  "Description.RoleRestrictedCategoryNoRoles": "No roles have been added to this category yet",
  "Description.UnrestrictDialog":
    "Unrestricting this category will immediately make all topics, comments, and replies in the category publicly visible.",
  "Message.RankReservedOnlyForGuest":
    "Ranks must be between {minRankPlusOne} and {maxRank}. {minRank} is reserved for guests.",
  "Action.ReenableForums": "Re-enable Forums",
  "Message.ForumsUnavailableTitle": "Forums are unavailable to your members.",
  "Message.ForumsUnavailableContent": "Your community members are not able to view forums.",
  "Message.ForumsLimitedTitle": "Forums are limited for your members.",
  "Message.ForumsLimitedContent": "Creating posts and comments is disabled in this community.",
  "Message.ReenableForumsSuccess": "Forums re-enabled successfully",
  "Message.ReenableForumsFail": "Failed to re-enable forums",
  "Description.CreatePostDisabled": "You are unable to post in locked forums",
  "Description.ReplyCommentDisabled": "You are unable to reply in locked forums",
  "Title.ForumsUnavailable": "Forum unavailable",
  "Description.ForumsUnavailable": "This forum is not accessible to you at this time.",
  "Heading.UnrestrictDialog": "Are you sure you want to make this category public?",
  "Heading.RestrictedCategoriesAgeCheck": "Managing some permissions requires an age check",
  "Description.RestrictedCategoriesAgeCheck": "It just takes a quick second.",
  "Error.AssetUploadFailed": "Image upload failed. Please try again in a moment.",
  "Heading.SupportTicketEducationTitle": "New bug reporting",
  "Label.SupportTicketMenuOption": "Add a bug report",
  "Label.SupportTicketEducationDescription": "Quickly report issues directly to the creator.",
  "Heading.SupportTicketDetails": "Bug report details",
  "Label.SupportTicketDetailsSubtitle":
    "How can the creator help? Report details are kept private.",
  "Label.SupportTicketWhereField": "Where did this happen?",
  "Label.SupportTicketDeviceField": "What device are you using?",
  "Label.SupportTicketScreenshotsHint":
    "Select up to three images. All images are subject to moderation.",
  "Label.SupportTicketShareUserInfo": "Share user information with creator",
  "Label.SupportTicketShareUserInfoHint": "This helps the creator support the correct account.",
  "Label.SupportTicketDetails": "Details",
  "Label.SupportTicketDetailsPlaceholder":
    "Include anything relevant about the issue, like the game version and how to reproduce the steps.",
  "Label.SupportTicket": "Bug report",
  "Label.AddAttachment": "Add attachment",
  "Label.SupportTicketDeviceCurrent": "This device",
  "Label.SupportTicketDeviceVrHeadset": "VR Headset",
  "Label.SupportTicketDeviceOther": "Other",
  "Heading.SupportTicketScreenshots": "Add screenshots ({uploadedCount}/{maxCount})",
  "Heading.BugReportingForumsEnabledUpsell": "Turn forum bug reports into trackable tickets",
  "Heading.BugReportingForumCategoriesUpsell": "Manage bug reporting",
  "Description.BugReportingForumCategoriesUpsell":
    "Select the roles in each category that can attach bug reports below",
  "Label.CreateBugReports": "Attach bug reports",
  "Description.BugReportingForumsEnabledUpsell":
    "Skip the manual work of copying threads to other tools for triage. Players can now file bugs directly in forums, which will automatically route straight to your Creator Hub helpdesk queue.",
  "Heading.BugReportingEnableForumsUpsell": "Unlock forum bug reports",
  "Description.BugReportingEnableForumsUpsell":
    "To automatically route player bug reports from forums to your Creator Hub Helpdesk queue, you must first enable your community forums in settings.",
  "Label.SupportTicketStatusOpen": "Open",
  "Label.SupportTicketStatusNeedsInfo": "Needs info",
  "Label.SupportTicketStatusFixed": "Fixed",
  "Label.SupportTicketStatusWontFix": "Won't fix",
  "Label.SupportTicketStatusCantFix": "Can't fix",
  "Label.SupportTicketStatusRobloxIssue": "Roblox issue",
  "Label.SupportTicketStatusViewTooltip": "View bug report",
  "Action.BugReportingTurnOn": "Turn on",
  "Action.BugReportingEnable": "Enable",
  "Heading.PostUnavailable": "Post unavailable",
  "Description.PostUnavailable": "This post is not accessible to you at this time.",
  "Label.SupportTicketDeviceGroupComputer": "Computer",
  "Label.SupportTicketDeviceGroupMobile": "Mobile & Tablet",
  "Label.SupportTicketDeviceGroupConsole": "Console",
  "Label.SupportTicketDeviceGroupVr": "Virtual Reality",
  "Action.ShowHiddenMessage": "Show hidden message",
  "Action.HideHiddenMessage": "Hide hidden message",
  "Label.WhyHiddenTitle": "Why are these messages hidden?",
  "Label.WhyHiddenBody": "These messages match other messages that users have hidden frequently.",
  "Label.HiddenMessageBadge": "Hidden message",
  "Action.ShowHiddenMessages": "Show {count} hidden messages",
  "Action.HideHiddenMessages": "Hide {count} hidden messages",
  "Action.HideHiddenPost": "Hide hidden post",
  "Action.HideHiddenPosts": "Hide {count} hidden posts",
  "Action.ShowHiddenPost": "Show hidden post",
  "Action.ShowHiddenPosts": "Show {count} hidden posts",
  "Label.HiddenPostBadge": "Hidden post",
  "Label.WhyHiddenPostsBody": "These posts match other posts that users have hidden frequently.",
  "Label.WhyHiddenPostsTitle": "Why are these posts hidden?",
  "Heading.CommunityTiersDisclosureBanner": "Access to some community features has been updated",
  "Description.CommunityTiersDisclosureBanner":
    "Some features and capabilities are now managed by the community's tier. This may affect which features some users can access.",
  "Heading.AnnouncementViews": "Views",
  "Heading.AnnouncementEngagement": "Engagement",
  "Heading.AnnouncementDeliveries": "Notifications delivered",
  "Label.DeletePostConfirmation": "Are you sure you want to delete this post?",
  "Label.DeleteCommentConfirmation": "Are you sure you want to delete this comment?",
  "Label.DeleteReplyConfirmation": "Are you sure you want to delete this reply?",
  "Label.PreventSimilarContent": "Prevent similar content",
  "Description.PreventSimilarContent":
    "We'll automatically hide similar content in this community from now on.",
  "Title.CommunityCompletionForumCard": "Start discussions",
  "Action.CommunityCompletionAnnouncementCard": "Post announcement",
  "Heading.CommunityCompletion": "Complete your community",
  "Action.CommunityCompletionHideForNow": "Hide for now",
  "Title.CommunityCompletionAnnouncementCard": "Reach everyone",
  "Description.CommunityCompletionAnnouncementCard":
    "Announcements notify members even when offline.",
  "Description.CommunityCompletionForumCard": "Forums give members a place to ask and share.",
  "Action.CommunityCompletionForumCard": "Enable forums",
  "Title.CommunityCompletionCoverPhotoCard": "Attract visitors",
  "Description.CommunityCompletionCoverPhotoCard": "Cover photos turn visitors into members.",
  "Action.CommunityCompletionCoverPhotoCard": "Add cover photo",
  "Title.CommunityCompletionEventCard": "Fill your servers",
  "Description.CommunityCompletionEventCard": "Events give your community a time to play together.",
  "Action.CommunityCompletionEventCard": "Create event",
  "Label.Private": "Private",
  "Action.RemoveTicket": "Remove ticket",
  "Message.UpdateRolesetPermissions":
    "{actor} updated roleset {rolesetName}'s permissions on {entityType} {entityName}.",
  "Message.UpdateRoleSetPermissionsAdded": "Added: {addedPermissions}.",
  "Message.UpdateRoleSetPermissionsRemoved": "Removed: {removedPermissions}.",
  "Action.LearnMoreLinkButton": "Learn more",
  "Label.UpdateRoleSetPermissions": "Update Role Permissions",
  "Description.ForumsNotAvailable":
    "The following requirements must be met before activating forums. Continue to learn more.",
  "Label.CapabilityAllAges": "All ages",
  "Description.TierProfessional": "Expand social features to 13+ & more",
  "Label.CapabilityForumsProfessional": "13+ write, 13+ read",
  "Label.RequirementAccountStatus": "Account status",
  "Label.RequirementAgeCheck": "Age check",
  "Description.RequirementAccountStatus": "Keep your account in good standing.",
  "Heading.Capabilities": "Capabilities",
  "Label.OwnerAgeChecked": "Owner age-checked",
  "Description.TierBasic": "Share updates and info with your members",
  "Heading.CommunityTier": "Community Tier",
  "Description.CommunityTierSubheading":
    "Complete the requirements below and expand your community's capabilities.",
  "Heading.Requirements": "Requirements",
  "Label.Current": "Current",
  "Action.Recheck": "Recheck",
  "Label.Checking": "Checking...",
  "Label.TierBasic": "Basic",
  "Label.TierSocial": "Social",
  "Label.TierProfessional": "Professional",
  "Description.TierSocial": "Give your followers social capabilities",
  "Label.CapabilityAnnouncements": "Announcements, Polls, and more",
  "Label.CapabilityForums": "Forums",
  "Label.CapabilityForumsSocial": "16+ write, 13+ read",
  "Description.RequirementAgeCheck": "Estimate your age with your camera.",
  "Label.RequirementIdVerification": "Identity verification",
  "Description.RequirementIdVerification": "Provide government ID.",
  "Label.RequirementTwoStep": "2-step verification",
  "Description.RequirementTwoStep": "Keep your account secure.",
  "Label.RequirementQualifiedMembers": "Qualified members",
  "Description.RequirementQualifiedMembers": "Reach 250 highly engaged users",
  "Heading.ForumsNotAvailable": "Forums are not available for your community",
  "Label.ActiveMembership": "Active membership",
  "Description.TierGatedForumWrite":
    "You must be 16+ to post. Complete an age-check to continue to post a comment.",
  "Message.SupportTicketLimitReached":
    "Cannot create a support ticket: the open support-ticket limit for this experience has been reached.",
  "Message.SupportTicketIneligible":
    "You cannot create a support ticket for this experience right now.",
  "Message.SupportTicketDetailsTooLong": "The support ticket details are too long.",
  "Action.Start": "Start",
  "Label.HiddenPostsHeader": "Posts below are hidden",
  "Label.HiddenPostHeader": "Post below is hidden",
  "Action.Reset": "Reset",
  "Label.NoSearchResults": "No results found",
  "Action.SearchForums": "Search for keywords or @users",
  "Action.SearchFilters": "Filters",
  "Action.Filters": "Filters",
  "Action.Apply": "Apply",
  "Label.SearchAll": "Any",
  "Label.SearchPosts": "Posts",
  "Label.SearchComments": "Comments",
  "Label.Category": "Category",
  "Label.AllCategories": "All categories",
  "Label.TimeRange": "Time range",
  "Label.TimeRangeDay": "Last 24 hours",
  "Label.TimeRangeWeek": "Last 7 days",
  "Label.TimeRangeMonth": "Last 30 days",
  "Label.TimeRangeAll": "All time",
  "Label.NoSearchResultsText": "Try different keywords or adjust your filters",
  "Label.MemberSearchHint": "Start typing to search members",
  "Label.NoMembersFound": "No members found",
  "Label.MemberSearchError": "Something went wrong. Please try again.",
  "Description.UnrestrictedMessagesCategory":
    "Members can send unrestricted messages and attach images in this category.",
  "Message.UpdateRolesetPropertiesVisibilityPrivate": "Visibility: Private",
  "Message.UpdateRolesetPositionTopRole": "highest role",
  "Label.UpdateRoleSetPosition": "Update Role Position",
  "Message.UpdateRolesetProperties": "{actor} updated roleset {roleSetName}'s properties",
  "Message.UpdateRolesetPropertiesName": "Name: {newName}",
  "Message.UpdateRolesetPropertiesDescription": "Description: {newDescription}",
  "Message.UpdateRolesetPropertiesColor": "Color: {newColor}",
  "Message.UpdateRolesetPropertiesVisibilityPublic": "Visibility: Public",
  "Message.UpdateRolesetPosition":
    "{actor} updated roleset {roleSetName}'s position from {oldPosition} to {newPosition}",
  "Message.UpdateRolesetPositionBelowRole": "below {roleAboveName}",
  "Label.UpdateRoleProperties": "Update Role Properties",
  "Error.SupportTicketOpenLimitReached":
    "You’ve reached the limit for open support tickets. Visit your Experience Support History to resolve open tickets.",
  "Error.SupportTicketIneligible": "You can’t submit a bug report for this experience right now."
};
window.Roblox &&
  window.Roblox.BundleDetector &&
  window.Roblox.BundleDetector.bundleDetected("DynamicLocalizationResourceScript_Feature.Groups");
