var Roblox = Roblox || {};
Roblox.LangDynamic = Roblox.LangDynamic || {};
Roblox.LangDynamic["Feature.Avatar"] = {
  "Heading.AvatarPageTitle": "Avatar Editor",
  "Label.ExploreCatalog": "Explore the catalog to find more clothes!",
  "Action.GetMore": "Get More",
  "Label.AskIfLoadingCorrectly": "Avatar isn't loading correctly?",
  "Label.RedrawUnavailable": "Avatar redraw is unavailable.",
  "Action.Redraw": "Redraw",
  "Label.DirectionsForScalingOptions":
    "Scaling options are available under Body category. Check {startBold}Body{rightArrow}Scale{endBold}",
  "Action.UserUnderstands": "Got it",
  "Heading.All": "All",
  "Heading.Accessories": "Accessories",
  "Heading.Clothing": "Clothing",
  "Heading.BodyParts": "Body Parts",
  "Heading.Animations": "Animations",
  "Heading.Outfits": "Outfits",
  "Label.Hat": "Hat",
  "Label.Hair": "Hair",
  "Label.Face": "Face",
  "Label.Neck": "Neck",
  "Label.Shoulders": "Shoulders",
  "Label.Front": "Front",
  "Label.Back": "Back",
  "Label.Waist": "Waist",
  "Label.Shirts": "Shirts",
  "Label.Pants": "Pants",
  "Label.TShirts": "T-Shirts",
  "Label.Gear": "Gear",
  "Label.HatAccessories": "Hat Accessories",
  "Label.HairAccessories": "Hair Accessories",
  "Label.FaceAccessories": "Face Accessories",
  "Label.NeckAccessories": "Neck Accessories",
  "Label.ShoulderAccessories": "Shoulder Accessories",
  "Label.FrontAccessories": "Front Accessories",
  "Label.BackAccessories": "Back Accessories",
  "Label.WaistAccessories": "Waist Accessories",
  "Label.Faces": "Faces",
  "Label.Head": "Head",
  "Label.Heads": "Heads",
  "Label.Torso": "Torso",
  "Label.Torsos": "Torsos",
  "Label.LeftArms": "Left Arms",
  "Label.RightArms": "Right Arms",
  "Label.LeftLegs": "Left Legs",
  "Label.RightLegs": "Right Legs",
  "Label.SkinTone": "Skin Tone",
  "Label.Scale": "Scale",
  "Heading.Packages": "Packages",
  "Heading.Appearance": "Appearance",
  "Label.Walk": "Walk",
  "Label.Run": "Run",
  "Label.Fall": "Fall",
  "Label.Jump": "Jump",
  "Label.Swim": "Swim",
  "Label.Climb": "Climb",
  "Label.Idle": "Idle",
  "Label.IdleAnimations": "Idle Animations",
  "Label.ClimbAnimations": "Climb Animations",
  "Label.SwimAnimations": "Swim Animations",
  "Label.JumpAnimations": "Jump Animations",
  "Label.FallAnimations": "Fall Animations",
  "Label.RunAnimations": "Run Animations",
  "Label.WalkAnimations": "Walk Animations",
  "Heading.Costumes": "Costumes",
  "Label.MyCostumes": "My Costumes",
  "Label.PresetCostumes": "Preset Costumes",
  "Message.RedrawFloodchecked":
    "You have redrawn your avatar too many times, please try again later.",
  "Message.RedrawThumbnailFailed": "Failed to redraw thumbnail.",
  "Message.FailedLoadRecent": "Failed to load recent items.",
  "Message.EmptyRecentItems": "You don't have any recent items.",
  "Heading.RenameOutfit": "Rename Outfit",
  "Description.RenameOutfit": "Choose a new name for your outfit.",
  "Action.RenameOutfit": "Rename",
  "Heading.CreateNewOutfit": "Create New Outfit",
  "Action.CreateNewOutfit": "Create",
  "Description.CreateNewOutfit": "An outfit will be created from your avatar's current appearance.",
  "Message.SuccessRenameOutfit": "Renamed outfit",
  "Message.SuccessDeleteOutfit": "Deleted outfit",
  "Message.SuccessUpdatedOutfit": "Updated outfit",
  "Message.SuccessCreateOutfit": "Created outfit",
  "Message.SuccessWoreOutfit": "Successfully wore outfit",
  "Message.EmptyListOfOutfits": "You don't have any outfits. Try creating some!",
  "Message.ReachedMaxOutfits": "You have reached the maximum number of outfits.",
  "Message.ErrorCreateOutfit": "Unable to create outfit, try again later.",
  "Message.InvalidOutfitName": "Name must be appropriate and less than 100 characters.",
  "Message.FailedUpdateDeletedOutfit": "The outfit you tried to update no longer exists.",
  "Message.ErrorUpdateOutfit": "Outfit update failed, please try again later.",
  "Message.FailedDeleteOutfit": "Failed to delete outfit.",
  "Message.ErrorRenameOutfit": "Failed to rename outfit.",
  "Message.ErrorWearOutfit": "Failed to wear outfit.",
  "Message.ErrorLoadOutfits": "Failed to load outfits.",
  "Label.NamePlaceholderOutfit": "Name your outfit",
  "Action.Update": "Update",
  "Action.Rename": "Rename",
  "Action.Delete": "Delete",
  "Action.Cancel": "Cancel",
  "Message.FailedWearPackage": "Failed to wear package.",
  "Message.SuccessSavedAccessories": "Saved accessories",
  "Message.EmptyAssetList": "You don't have any.",
  "Message.FailedLoadAssets": "Failed to load assets list.",
  "Message.ErrorUpdateWorn": "Error while updating worn items.",
  "Message.FailedUpdateScales": "Failed to update scales.",
  "Message.FailedUpdateType": "Failed to update avatar type.",
  "Message.FailedUpdateBodyColor": "Failed to update skin tone.",
  "Message.DefaultClothing":
    "Default clothing has been applied to your avatar - wear something from your clothing.",
  "Heading.Update": "Update",
  "Message.UpdateOutfit":
    "Do you want to update this {outfitType1}? This will overwrite the {outfitType2} with your avatar's current appearance.",
  "Heading.Delete": "Delete",
  "Message.DeleteOutfit": "Are you sure you want to delete this {outfitType}?",
  "Heading.AccessoriesChange": "Accessories Change",
  "Message.AccessoriesChange": "Are you sure you want to override your current look?",
  "Label.Costume": "Costume",
  "Label.Outfit": "Outfit",
  "Label.Clothes": "Clothes",
  "Heading.Body": "Body",
  "Label.Parts": "Parts",
  "Action.Save": "Save",
  "Message.Warning": "Warning",
  "Message.Loading": "Loading...",
  "Message.Success": "Success",
  "Message.HatLimitTooltip": "You can wear up to 3 hats",
  "Label.SwitchAvatarType":
    "Switch between classic R6 avatar and more expressive next generation R15 avatar",
  "Heading.Recommended": "Recommended",
  "Action.ThreeDimensions": "3D",
  "Action.TwoDimensions": "2D",
  "Description.AvatarEditorUpsell":
    "To change your look you will need to use the Avatar Editor on the App.",
  "Action.OpenRobloxApp": "Open Roblox App",
  "Action.Get": "Get",
  "Action.Buy": "Buy",
  "Message.SelectEnableScaling": "Select R15 to enable scaling.",
  "Heading.Scaling": "Scaling",
  "Action.Advanced": "Advanced",
  "Heading.CreateNewCostume": "Create New Costume",
  "Message.ErrorOutfitName": "Name can contain letters, numbers, and spaces.",
  "Heading.AdvancedOptions": "Advanced Options",
  "Heading.Recent": "Recent",
  "Label.Height": "Height",
  "Label.Width": "Width",
  "Label.BodyType": "Body Type",
  "Label.Proportions": "Proportions",
  "Heading.SkinToneBodyParts": "Skin Tone by Body Parts",
  "Action.Create": "Create",
  "Label.All": "All",
  "Label.LeftArm": "Left Arm",
  "Label.RightArm": "Right Arm",
  "Label.LeftLeg": "Left Leg",
  "Label.RightLeg": "Right Leg",
  "Action.SeeAll": "See All",
  "Action.Done": "Done",
  "Action.Close": "Close",
  "Message.UpdateThisOutfit":
    "Do you want to update this outfit? This will overwrite the outfit with your avatar's current appearance.",
  "Message.UpdateThisCostume":
    "Do you want to update this costume? This will overwrite the costume with your avatar's current appearance.",
  "Heading.DeleteOutfit": "Delete Outfit",
  "Heading.DeleteCostume": "Delete Costume",
  "Heading.UpdateOutfit": "Update Outfit",
  "Heading.UpdateCostume": "Update Costume",
  "Message.DeleteThisOutfit": "Are you sure you want to delete this outfit?",
  "Message.DeleteThisCostume": "Are you sure you want to delete this costume?",
  "Message.EmptyListForItem": "You don't have this item: {itemType}",
  "Message.MissingItemsFromOutfit": "Number of items that you don't own in this outfit: {number}",
  "Label.AssetIDPlaceholder": "Asset ID",
  "Message.PageUnavailable": "The avatar page is temporarily unavailable.",
  "Label.DirectionsForPackagePlacement":
    "Packages have been moved to Costumes. Check {startBold}Costumes{rightArrow}Preset Costumes{endBold}",
  "Heading.RenameCostume": "Rename Costume",
  "Description.RenameCostume": "Choose a new name for your costume.",
  "Description.CreateNewCostume":
    "A costume will be created from your avatar's current appearance.",
  "Message.SuccessRenameCostume": "Renamed costume",
  "Message.SuccessDeleteCostume": "Deleted costume",
  "Message.SuccessUpdatedCostume": "Updated costume",
  "Message.SuccessCreateCostume": "Created costume",
  "Message.SuccessWoreCostume": "Successfully wore costume",
  "Message.EmptyListOfCostumes": "You don't have any costumes. Try creating some!",
  "Message.ReachedMaxCostumes": "You have reached the maximum number of costumes.",
  "Message.ErrorCreateCostume": "Unable to create costume, try again later.",
  "Message.FailedUpdateDeletedCostume": "The costume you tried to update no longer exists.",
  "Message.ErrorUpdateCostume": "Costume update failed, please try again later.",
  "Message.FailedDeleteCostume": "Failed to delete costume.",
  "Message.ErrorRenameCostume": "Failed to rename costume.",
  "Message.ErrorWearCostume": "Failed to wear costume.",
  "Message.ErrorLoadCostume": "Failed to load costume.",
  "Label.NamePlaceholderCostume": "Name your costume",
  "Message.PresetCostumesDelay":
    "Note: We're doing some housekeeping, so it may take a few minutes for all your costumes to appear. Check again in a bit!",
  "Label.Equip": "Equip",
  "Message.ChooseEmoteSlot": "Choose a slot",
  "Label.YourEmotes": "Your Emotes",
  "Message.ErrorLoadEmotes": "Failed to load emotes.",
  "Message.ErrorDeleteEmote": "Failed to delete emote.",
  "Message.SuccessEquipEmote": "Equipped Emote",
  "Message.ErrorUnequipEmote": "Failed to unequip emote.",
  "Message.ErrorEquipEmote": "Failed to equip emote, please try again later.",
  "Message.SuccessUnequipEmote": "Unequipped emote",
  "Heading.Emotes": "Emotes",
  "Heading.EquipEmotes": "Equip Emotes",
  "Message.ChooseEmote": "Choose an Emote",
  "Label.R6": "R6",
  "Label.R15": "R15",
  "Message.EmotesInstructions": 'Go to "Animations" > "Emotes" > "Equip Emotes" to equip an emote.',
  "Message.ChooseEmoteSlotOrEmote": "Choose a slot or an Emote",
  "Label.BodyStyle": "Body Style",
  "Label.R6R15": "R6/R15",
  "Label.TShirt": "T-Shirt",
  "Label.Build": "Build",
  "Label.ExploreAvatarShop": "Explore the avatar shop to find more clothes!",
  "Action.Select": "Select",
  "Heading.RenameCharacter": "Rename Character",
  "Label.Creations": "Creations",
  "Label.Purchased": "Purchased",
  "Label.Outerwear": "Outerwear",
  "Label.Tops": "Tops",
  "Label.Bottoms": "Bottoms",
  "Label.LeftShoes": "Left Shoes",
  "Label.RightShoes": "Right Shoes",
  "Label.Shoes": "Shoes",
  "Label.ClassicShirts": "Classic Shirts",
  "Label.ClassicTShirts": "Classic T-Shirts",
  "Label.ClassicPants": "Classic Pants",
  "Label.Jacket": "Jacket",
  "Label.Jackets": "Jackets",
  "Label.Sweater": "Sweater",
  "Label.Sweaters": "Sweaters",
  "Label.Shorts": "Shorts",
  "Label.LeftShoe": "Left Shoe",
  "Label.RightShoe": "Right Shoe",
  "Label.DressesAndSkirts": "Dresses & Skirts",
  "Heading.Characters": "Characters",
  "Label.HeadAccessories": "Head Accessories",
  "Label.Classic": "Classic",
  "Label.LayeredClothingR15Warning": "Update your body type to R15 to enable this item.",
  "Label.LayeredClothingSwitchR6Warning":
    "R6 characters have limitations. If you switch, all unsupported items will be removed.",
  "Action.Switch": "Switch",
  "Message.ErrorAdvancedSaveHair": "Failed to save: A maximum of one hair is allowed.",
  "Message.ErrorAdvancedSave": "Failed to save: A maximum of {limitAmount} {assetType} is allowed.",
  "Message.ErrorAdvancedUnsupportedAssetType":
    "Failed to save: {assetType} are not supported in the advanced editor.",
  "Heading.CreateNewCharacter": "Create New Character",
  "Description.RenameC": "Choose a new name for your character.",
  "Description.CreateNewCharacter":
    "A character will be created from your avatar's current appearance.",
  "Message.SuccessRenameCharacter": "Renamed character",
  "Message.SuccessDeleteCharacter": "Deleted character",
  "Message.SuccessUpdatedCharacter": "Updated character",
  "Message.SuccessCreateCharacter": "Created character",
  "Message.SuccessWoreCharacter": "Successfully wore character",
  "Message.EmptyListOfCharacters": "You don't have any characters. Try creating some!",
  "Message.ReachedMaxCharacters": "You have reached the maximum number of characters.",
  "Message.ErrorCreateCharacter": "Unable to create character, try again later.",
  "Message.FailedUpdateDeletedCharacter": "The character you tried to update no longer exists.",
  "Message.ErrorRenameCharacter": "Failed to rename character.",
  "Message.ErrorWearCharacter": "Failed to wear character.",
  "Message.ErrorLoadCharacter": "Failed to load character.",
  "Label.NamePlaceholderCharacter": "Name your character",
  "Message.LCSortEntry": "Adjust clothing order",
  "Description.RenameCharacter": "Choose a new name for your character.",
  "Message.ErrorUpdateCharacter": "Character update failed, please try again later.",
  "Message.FailedDeleteCharacter": "Failed to delete character.",
  "Title.UnableToEquip": "Unable To Equip",
  "Heading.UpdateCharacter": "Update Character",
  "Message.UpdateThisCharacter":
    "Do you want to update this character? This will overwrite the character with your avatar's current appearance.",
  "Heading.DeleteCharacterTitle": "Delete Character",
  "Message.DeleteThisCharacter": "Are you sure you want to delete this character?",
  "Title.LCLimit": "You've reached the limit",
  "Label.LCLimit":
    "You've layered the maximum number of clothing items. Unequip one to try another.",
  "Label.ClassicFaces": "Classic Faces",
  "Label.ClassicHeads": "Classic Heads",
  "Label.HeadBody": "Head & Body",
  "Label.HeadStyle": "Head Style",
  "Label.HeadType": "Head Type",
  "Label.Style": "Style",
  "Label.LeftInitial": "L",
  "Label.Right": "R",
  "Label.RightInitial": "R",
  "Label.TryOnManagerDescriptor": "Total: {numItems} items",
  "Action.Marketplace": "Marketplace",
  "Label.ExploreMarketplace": "Explore the marketplace to find more clothes!",
  "Label.MyCreationsOnly": "My creations only",
  "Label.Character": "Character",
  "Label.Curator": "Curator",
  "Label.TotalValue": "Total Value",
  "Label.HeadRefinement.Title": "Head Shape",
  "Label.HeadRefinement.Description": "Choose a head style to use with your classic face.",
  "Label.HeadRefinement.Description.Unsupported":
    "Adjustment is not available for this head style.",
  "Label.HeadRefinement.Adjust.Tooltip": "Adjust head here!",
  "Label.HeadRefinement.CombinedCategories.Tooltip": "All Classics are now under Heads",
  "Label.HeadRefinement.Adjust.Title": "Head Adjustment",
  "Label.Title.AccessoryAdjustment": "Accessory Adjustment",
  "Label.Title.BodyShape": "Body Shape",
  "Label.Title.HeadAdjustment": "Head Adjustment",
  "Label.Title.ClothingLayering": "Clothing Layering",
  "Label.Title.Inventory": "Inventory",
  "Label.Title.Emotes": "Emotes",
  "Label.Title.ProfilePhoto": "Profile Photo",
  "Label.Title.AvatarSwitcher": "My Avatars",
  "Label.Title.MyInventory": "My Inventory",
  "Heading.RecentlyAcquired": "Recently Added",
  "Heading.RecentlyWorn": "Recently Worn",
  "Label.Title.Save": "Save",
  "Label.Title.AddNewAvatar": "Add as New Avatar",
  "Label.Title.UpdateAvatar": "Replace Existing Avatar",
  "Label.Title.ManageAvatars": "Manage Avatars",
  "Label.Title.ReplaceAvatar": "Replace Avatar",
  "Message.SaveSuccess": "Avatar saved",
  "Message.SaveSuccessWithInvalidAssets":
    "Avatar saved. Some items were removed because they aren't available right now.",
  "Message.SaveThrottled": "Please wait a few seconds before saving again",
  "Message.SaveFailure": "Your avatar could not be saved. Please try again later.",
  "Label.Title.BlockingSavePrompt": "Save Avatar?",
  "Label.Message.BlockingSavePrompt": "If you don't save now, you'll lose all changes.",
  "Action.MyPublishedAvatars": "My Published Avatars",
  "Action.EditOutfit": "Edit outfit",
  "Action.LoadMore": "Load More",
  "Action.SelectColor": "Select color",
  "Feature.DisplayName.ErrorMessage.SomethingWentWrong":
    "Something went wrong. Please try again later.",
  "Label.Title.SaveToMyAvatars": "Save to my avatars",
  "Label.Title.DuplicateAvatar": "Duplicate Avatar",
  "Label.Message.DuplicateAvatar": "It looks like you have previously saved a similar avatar:",
  "Label.Title.AvatarName": "Enter Avatar Name",
  "Label.Title.DeleteSingleAvatar": "Delete This Avatar?",
  "Label.Title.DeleteMultipleAvatars": "Delete {count} Avatars?",
  "Label.Message.DeleteAvatars": "This cannot be undone.",
  "Label.Title.AddToMyAvatars": "Add to my avatars",
  "Label.Title.WearAfterPurchase": "Wear after purchase",
  "Label.Title.WearAndSaveAfterPurchase": "Wear and save after purchase",
  "Label.Avatars": "Avatars",
  "Label.BodyParts": "Body Parts: {bodyPart}",
  "Label.AddManage": "Add/Manage",
  "UnavailableItems.ConfirmText": "OK",
  "Message.LooksAvatarSaved": "You can always edit your avatar name in customization",
  "Heading.LooksAvatarSaved": "Avatar Saved!",
  "Label.Bodysuits": "Bodysuits",
  "Label.Makeup": "Makeup",
  "Label.Looks": "Looks",
  "Label.LipMakeup": "Lips",
  "Label.Eyelashes": "Eyelashes",
  "Label.Eyebrows": "Eyebrows",
  "Label.FullBody": "Full Body",
  "Label.EyeMakeup": "Eyes",
  "Label.HexColor": "Hex Color",
  "Label.HexPlaceholder": "#FFF000 or FFF000",
  "Label.HeadRefinement.DH.Title": "Classic Shapes",
  "Title.BuyMakeup": "Buy Makeup Look",
  "Label.BuyMakeupQuestion": "Would you like to buy this makeup look?",
  "Label.Title.AddToMyMakeupLooks": "Add to my makeup looks",
  "Label.HourAbbreviated": "{hours}h",
  "Label.DayAbbreviated": "{days}d",
  "Label.MinuteAbbreviated": "{minutes}m",
  "Title.TimedOptionsExpiredModalTitle": "{number} Expired items on this avatar",
  "Body.TimedOptionsExpiredItemsBody": "Buy these items again to use it",
  "Label.Title.MakeupLayering": "Makeup Layering",
  "Title.LayeredMakeupSortPage": "Makeup Layering",
  "Message.UnknownErrorCreatingMakeupLook": "An unknown error occurred. Makeup look not created.",
  "Heading.MakeupLookSaved": "Makeup look saved!",
  "Message.MakeupLookSaved": "You can always edit your makeup look name in customization",
  "Label.Permanent": "Permanent",
  "Label.TimedOptionDays": "{days} days",
  "Heading.TimedOptionExpiredItems": "{count} Expired items on this avatar",
  "Message.TimedOptionViewExpiredItems": "View expired items",
  "Label.YourBalanceAfterTransaction":
    "Your balance after this transaction will be {remainingBalance}.",
  "Title.EnhancedAvatarHeads": "Enhanced Avatar Heads",
  "Message.EnhancedAvatarHeads":
    "Classic heads now support facial animations. Find all your heads under Heads, and adjust head shape and facial animations in Head Adjustment.",
  "Label.FacialAnimation": "Facial Animation",
  "Label.HeadRefinement.FacialAnimation": "Facial Animation",
  "Message.LayeredMakeupSortNoEquipped": "No Layered Makeup Items Equipped. Equip Item to Edit.",
  "Message.AvatarEditingDisabled": "Avatar editing is disabled",
  "Message.AvatarEditingDisabledTime": "Avatar editing is disabled until {date}",
  "Heading.Expired": "Expired",
  "Message.NoExpiredItems": "You don't have any expired items",
  "Label.Props": "Props",
  "Label.FullMasks": "Full Masks",
  "Label.HandAndArm": "Hand & Arm",
  "Heading.BuyItem": "Buy Item",
  "Backgrounds.Title": "Backgrounds",
  "Message.SwitchedTo2DToShowBackgrounds": "Switched to 2D to show backgrounds",
  "Message.BackgroundsArentSupportedIn3D":
    "Backgrounds aren't supported in this view. Switch to 2D view.",
  "Label.ProfileFrames": "Frames",
  "Label.ProfileFramesUnlockBanner": "Unlock frames with Plus",
  "Title.FindYourStyle": "Find Your Style",
  "Label.ProfileFrame.Pink": "Pink",
  "Label.ProfileFrame.Ruins": "Ruins",
  "Label.ProfileFrame.Scifi": "Scifi",
  "Label.ProfileFrame.Wings": "Wings",
  "Label.ProfileFrame.Gold": "Gold",
  "Label.ProfileFrame.Silver": "Silver",
  "Label.ProfileFrame.Black": "Black",
  "Label.ProfileFrame.White": "White",
  "Label.ProfileFrame.Turquoise": "Turquoise",
  "Label.ProfileFrame.Redcliff": "Redcliff"
};
window.Roblox &&
  window.Roblox.BundleDetector &&
  window.Roblox.BundleDetector.bundleDetected("DynamicLocalizationResourceScript_Feature.Avatar");
